### PR TITLE
Added copyMessage method

### PR DESCRIPTION
**Pull request by Aazerra**
#1031

### CODE REVIEW

**Comment by Aazerra** [comment]
i added
but idk i did good or not before accept and merge check the code

**Comment by Badiboy** [comment]
```
        return types.Message.de_json(
            ...
```

image

https://core.telegram.org/bots/api#copymessage

**Comment by Badiboy** [comment]
```
def copy_message(self, chat_id, from_chat_id, message_id, caption=None, parse_mode=None, caption_entities=None,
                     reply_to_message_id=None, allow_sending_without_reply=None, reply_markup=None,
                     disable_notification=None, timeout=None):
```

I suppose it's better to keep original parameters order:
image

**Comment by Badiboy** [comment]
```
    if caption_entities is not None:
        payload['caption_entities'] = caption_entities
```

Entities are classes and cannot be passed like this.

image

**Comment by Badiboy** [comment]
```
  if reply_markup is not None:
        payload['reply_markup'] = reply_markup
```

reply_markup cannot be passed like this. Check other methods who have it.

**Comment by Badiboy** [comment]
And no reason to leave "FIXME".

It's just very brief review. Things are not so easy, you should definitely pay attention when commiting to public library.

**Comment by Aazerra** [comment]
Oh sry
I will pay more attention 
I will fix this thing and push it again

**Comment by Aazerra** [comment]
i added to_json to entites but need to added on other things too ( new update of API added entities to too many types )
the function of _covert_entities i created i thing have a bug  on isinstance because i used first element of array
if its wrong please let me know

**Pull request merged**
