### PR TITLE
Update Add the blockquote function formatting.py

### PR DESCRIPTION
**Pull request by HACKS-EXE**
For this code to work it needs the approval of https://github.com/eternnoir/pyTelegramBotAPI/pull/2091 and the other way around too

To make this change I researched formatting: https://markdown.net.br/sintaxe-basica/#blockquote-muiltiple-paragraphs

My tests are in the comments

image

### CODE REVIEW

**Comment by Badiboy** [comment]
1.
image

**Comment by HACKS-EXE** [comment]
> 2. Where you got that
>    `> {}`
>    will make text citation? Ay proofs?

I made the code myself

**Comment by HACKS-EXE** [comment]
> 2. Where you got that
>    `> {}`
>    will make text citation? Ay proofs?


https://github.com/eternnoir/pyTelegramBotAPI/assets/88611462/221c7f70-666d-4980-bbb4-941ee2279e9d

**Comment by HACKS-EXE** [comment]
> 2. Where you got that
>    `> {}`
>    will make text citation? Ay proofs?

image

image

image

This is how I left it and made my script

**Comment by HACKS-EXE** [comment]
> image

To add this formatting I researched Markdown formatting here: https://markdown.net.br/sintaxe-basica/

**Comment by Badiboy** [comment]
> To add this formatting I researched Markdown formatting here: https://markdown.net.br/sintaxe-basica/

You cannot invent markdown yourself.

https://core.telegram.org/bots/api#sendmessage

Here are all markdown options, available for sending messages.

**Comment by HACKS-EXE** [comment]
> > To add this formatting I researched Markdown formatting here: https://markdown.net.br/sintaxe-basica/
> 
> You cannot invent markdown yourself.
> 
> https://core.telegram.org/bots/api#sendmessage
> 
> Here are all markdown options, available for sending messages.

I didn't create something that doesn't exist, in the latest telegram updates, blockquotes were added, which allows the user to format the message using the blockquote to highlight the message, what I did was just put the blockquote to work in the telebot library, I didn't create the blockquote it already exists in Markdown format, I just added the Markdown formatting blockquote to the formatting.py code that is located in the telebot folder.

Take a look at the example below.

Hello, this is how to put the blockquote in messages in telegram.

> Hi, this is how to put blockquotes using the bot
To put blockquotes in the bot you have to leave a '>' at the beginning of each text.

image
image

**Comment by coder2020official** [comment]
Btw, since the bot api got released, we can think of this again

**Comment by coder2020official** [comment]
Could you also implement hcite before we merge it?

**Comment by coder2020official** [comment]
@Badiboy this should work according to bot doc, are you ok with this now?

**Comment by coder2020official** [comment]
image
Doc said to remove space too
@Badiboy check out

**Comment by Badiboy** [comment]
> return '>{}'.format(escape_markdown(content) if escape else content)

image

I think the function **mcite** needs to check for /n and add ">" for every logical line. It can be made with splitting by /n, then add ">" and then join back.

**Review by Badiboy — CHANGES_REQUESTED** [review]
Commen is given above.

**Comment by HACKS-EXE** [comment]
> Could you also implement hcite before we merge it?

I've added https://github.com/HACKS-EXE/Zaquiles-PY-TeleBot-API/blob/master/telebot/formatting.py#L84-L112
https://github.com/HACKS-EXE/Zaquiles-PY-TeleBot-API/blob/master/examples/formatting_example.py#L35

**Pull request closed without merging**
