### PR TITLE
Check if the event loop is running (async telebot)

### PR DESCRIPTION
**Pull request by David256**
## Description
Check if the event loop is running, otherwise create a new event loop.

## Describe your tests
The changes were tested on a bot of our own because this library does not yet have tests for async.

Python version: Python 3.9.2

OS: Debian GNU/Linux 11

### CODE REVIEW

**Comment by coder2020official** [comment]
Why?

**Comment by David256** [comment]
Usually raises `Event loop is closed` the first time when AsyncTeleBot sends `getUpdates`.

**Comment by coder2020official** [comment]
This was a windows bug; There are no such issues on other platforms;
And, setting new event loop on object creation is a very bad idea.

**Comment by David256** [comment]
Well, simply calling `asyncio.get_event_loop()` has the same effect because it checks for an event loop. But, this was the solution I found for this. 🤔

**Pull request closed without merging**
