### PR TITLE
Update util.py

### PR DESCRIPTION
**Pull request by SwissCorePy**
Improved `split_string` function. Splits text into more meaningful parts.

### CODE REVIEW

**Comment by Badiboy** [comment]
I think it's not possible to change existing function begaviour to save the backward compatibility of the legacy code behaviour.

It's possible to add your improvements either as a separate funtion or as an optional function behaviour (that will be enabled either with GLOBAL_CONSTANT or with optional parameter). 

Me personally prefer separate function, but the choice is up to you.

**Comment by SwissCorePy** [comment]
> I think it's not possible to change existing function begaviour to save the backward compatibility of the legacy code behaviour.
> 
> It's possible to add your improvements either as a separate funtion or as an optional function behaviour (that will be enabled either with GLOBAL_CONSTANT or with optional parameter).
> 
> Me personally prefer separate function, but the choice is up to you.

It is backward compatible. the only difference ist that `chars_per_string` is now optional

**Comment by Badiboy** [comment]
> It is backward compatible. the only difference ist that chars_per_string is now optional.

No, it will not produce absolutely the same result due to new splitting points ("/n" etc), thus is will not be fully compatible. I'll appreciate new function.

**Comment by SwissCorePy** [comment]
ok i will make it a new function.

**Pull request closed without merging**
