### PR TITLE
UPG: Bot API 4.5 support

### PR DESCRIPTION
**Pull request by tohabyuraev**

### CODE REVIEW

**Comment by tohabyuraev** [comment]
The last two commits support Bot API 4.5 issue #775

**Comment by tohabyuraev** [comment]
Last commit supports issue #838

**Comment by Badiboy** [comment]
image

Did you really think that if you place arbitrary parameter in class constructor, it will work fine?

It shows that you NEVER run the bot with your updates. You never run any test. 

I appreciate your willing to participate, but I have no time to make a codereview for you. All your pull requests contains elementary bugs that can be discovered by simply run the code.

**Comment by Badiboy** [comment]
image

You do not understand what's written there and how it works. You make blind changes without understanding. The same problem was when you started refactor "to_dic -> to_dict" and break everything.

**Comment by tohabyuraev** [comment]
Yes, there is a flaw. I forgot to add one field to the constructor of the class. I saw this error and wanted to fix it in the next commit.

But as for to_dic -> to_dict, each method was inside a separate class and did not affect the others. And it was an inaccuracy that needed to be fixed.

I see some flaws in the code and would like to fix them. Unfortunately, I'm not perfect.

**Comment by Badiboy** [comment]
Let's try...

**Pull request merged**
