### PR TITLE
Fix some type hints and warnings

### PR DESCRIPTION
**Pull request by Badiboy**
## Description
Fix some type hints and warnings

1. Several typehint fixes
2. 1 return bug fix
3. BuiltIn hints suppressed to make hint check easier

### CODE REVIEW

**Comment by coder2020official** [comment]
LGTM

**Comment by Badiboy** [comment]
Thanks.

Damn. I commited https://github.com/eternnoir/pyTelegramBotAPI/issues/2382 before merge and it fell here also. Could you please approve also?

**Comment by coder2020official** [comment]
I'd add typehints

**Comment by Badiboy** [comment]
Typehints added

**Review by coder2020official — APPROVED** [review]

**Pull request merged**
