### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by snxx-lppxx**
Removed long links. Shortened the code horizontally.

### CODE REVIEW

**Comment by Badiboy** [comment]
image

Could you please provide the proof link that this way to show badges is correct?

**Comment by Badiboy** [comment]
image

It's not Italic and Bold. It's items and Italic with * reference.

**Comment by Badiboy** [comment]
Generally I see no reason that most of shorten links (especially with Bot API versions) splitted into several places are more comfortable that long links. 

I propose to come back to discuss Readme code design after you start commiting lot of valuable changes to the Readme and definitely face with some inconvenience doing this...

**Review by BLUE-DEVIL1134 — CHANGES_REQUESTED** [review]
As I Saw,
You Didn't Added Links, You Just Replaced The Links With Some Reffrenced Text..

**Comment by Badiboy** [comment]
> As I Was Seeing,
> You Didn't Added Links, You Just Replaced The Links With Some Reffrenced Text..

You should Seeing better.

**Comment by snxx-lppxx** [comment]
This is what caused the error.

**Comment by Badiboy** [comment]
**I propose to come back to discuss Readme code design after you start commiting lot of valuable changes to the Readme and definitely face with some inconvenience doing this...**

**Pull request closed without merging**
