### PR TITLE
A Google Cloud Functions webhook

### PR DESCRIPTION
**Pull request by fgallaire**
Working great now

### CODE REVIEW

**Comment by fgallaire** [comment]
Now working great

**Comment by Badiboy** [comment]
You have two pull requests. What is the difference? Or close the outdated if any.

**Comment by fgallaire** [comment]
> You have two pull requests. What is the difference? Or close the outdated if any.

Now only one, this one !

The code is working great now, I use it.

**Comment by Badiboy** [comment]
1. Why the function is named

> webhook_functions

while it can be used **only for Google Cloud Functions**? If this, it should have name like
_webhook_google_cloud_
or something like that.

2. How this function can/should be used? Is it obvious for ones who use Google? (I did not use it, so it's a question)

**Comment by Badiboy** [comment]
image

It's enormous that different function returns have different signatures.

**Comment by fgallaire** [comment]
> image
> 
> It's enormous that different function returns have different signatures.

It's Flask API, the most used web framework in the Python world.

**Comment by Badiboy** [comment]
Okay, thank you.

**Comment by fgallaire** [comment]
>     1. Why the function is named
> 
> 
> > webhook_functions
> 
> while it can be used **only for Google Cloud Functions**? If this, it should have name like
> _webhook_google_cloud_
> or something like that.

The name of the service is _Functions_ and so the name of the function. As it's a generic name, I agree something more is needed, as a service form the _Google Cloud_, I think add just _google_ is shorter and so better.

Done.

>     1. How this function can/should be used? Is it obvious for ones who use Google? (I did not use it, so it's a question)

Yes it's quite obvious, the function do all the boilerplate.

```
def webhook(request):
    util.webhook_google_functions(bot, request)
```

**Comment by fgallaire** [comment]
> Okay, thank you.

Thank you a lot for your work.

**Pull request merged**
