### PR TITLE
Created create_invite_link.py

### PR DESCRIPTION
**Pull request by DevAdvik**
Added create_chat_invite_link() function example

## Description
This is an example code on how to create invite links for groups automatically via bot

## Describe your tests
1 week test using custom bot and a group, works like a charm

Python version: 3.9

OS: Ubuntu 22.04 LTS

### CODE REVIEW

**Comment by Badiboy** [comment]
image

What's that?

**Comment by Badiboy** [comment]
Thank you!

**Comment by dannkunt** [comment]
@DevAdvik Why don't check your code before make pull request?
@Badiboy Why don't you check before merge?

This code can't even start

**Comment by DevAdvik** [comment]
What error are you getting? I'm literally running the same code for another group for about 2 weeks or so and it works perfetly fine.
What error are you running into?

**Comment by dannkunt** [comment]
@DevAdvik 
изображение
There is not markaps in telebot directly, they are in telebot.types.
You missed comma on the line 24
And thats at the end of the code?

**Comment by coder2020official** [comment]
Bad example. Please improve the example

**Comment by DevAdvik** [comment]
@dannkunt Oh yep, I wrote the import lines myself and then copied the rest. Seems like I forgot putting `.types`, apologies for that, I'll fix it asap

**Comment by coder2020official** [comment]
Do not forget to remove while True for polling, and threading module which is not used.

**Comment by Badiboy** [comment]
@dannkunt So much ado about nothing. You'll loose less time ti fix then to write here.

**Comment by DevAdvik** [comment]
@coder2020official Why is while loop for polling bad?

**Comment by dannkunt** [comment]
@Badiboy I am already reworking examples, what if there was a virus in the example? How do you check pull requests?
изображение

**Comment by DevAdvik** [comment]
@dannkunt Code is checked for basic functionalities, just not thoroughly I guess. At a glance, you can determine if all the written lines are related to pyTelegramBotAPI and do stuff, but not enough to check minor mistakes.
That's why I guess this mistake was merged

**Pull request merged**
