### PR TITLE
Fix ChatBoostSource issues

### PR DESCRIPTION
**Pull request by Badiboy**
## Description
Fix ChatBoostSource issues

1. "source" is temporary made optional
2. source types are parsed correctly

### CODE REVIEW

**Comment by coder2020official** [comment]
LGTM, but let's wait for the answer from bot API dev

**Comment by Badiboy** [comment]
> but let's wait for the answer from bot API dev

By making source "Optional" we do not break anything, just fix the current issue for users. When we got answer - we cann roll it back, it's not a problem :)

**Comment by coder2020official** [comment]
https://github.com/tdlib/telegram-bot-api/blob/ade0841d41b7126c2d908475291a5e1cd8a1b905/telegram-bot-api/Client.cpp#L3345
It is not optional; I doubt that it is an API bug
We have to investigate the issue further

**Comment by Badiboy** [comment]
It's wrong to wait more. 

@coder2020official When something will change - will make an update.

**Pull request merged**
