### PR TITLE
UPG: Add BotCommand, setMyCommands

### PR DESCRIPTION
**Pull request by tohabyuraev**
Hello. I would like to add a new data type and method. Perhaps there are errors. Ready for comments.

### CODE REVIEW

**Comment by Badiboy** [comment]
Looks fine, thank you )

**Comment by Badiboy** [comment]
image

You start refactoring dic->dict, but not finished. 

Please, attentively check other occurence of to_dic everywhere.

**Comment by tohabyuraev** [comment]
Ok. I'll try fix it.

**Comment by Badiboy** [comment]
Thank you.

For the future: refactoring of the existing code is not so easy, so either please be accurate or avoid this. :)

**Comment by tohabyuraev** [comment]
1. I have a question. Somewhere the to_dic method is used. But where is it defined?
2. Can I write to you and discuss some issues?

**Comment by Badiboy** [comment]
No time for discussion now, sorry.
I fixed issues here: https://github.com/eternnoir/pyTelegramBotAPI/pull/831

**Pull request merged**
