### PR TITLE
Aiohttp version updated; Python 3.12 support

### PR DESCRIPTION
**Pull request by coder2020official**

### CODE REVIEW

**Comment by coder2020official** [comment]
@Badiboy looks like we have to update our installer :(
https://github.com/python/cpython/issues/95299

**Comment by Badiboy** [comment]
Add setuptools to requirements?

**Comment by coder2020official** [comment]
Is it a good idea?

**Comment by coder2020official** [comment]
https://peps.python.org/pep-0518/
https://peps.python.org/pep-0517/
We need changes, specifically we need pyproject.toml and other things; we should remove setup.py to follow future releases

**Pull request closed without merging**
