### PR TITLE
I18N class for sync telebot and middleware for async

### PR DESCRIPTION
**Pull request by abdullaev388**
In this example i added two new tools.

First is I18N class which is in util.py. It is based on gettext util. For command line interface used babel's pybabel script.
Also i added an example for it where you can see how to use gettext for singular translations and ngettext for plural translations.
It's not full-featured as async version because sync telebot does not have class-based middlewares.

Async version is full-featured middleware. For middlewares i created a new file asyncio_middlewares.py
In order to use it installing babel package is recommended. This middleware also has lazy_gettext to handle 'text buttons' in multilanguage bot.

Both examples have very descriptive doc's in the beginning of main.py files.

### CODE REVIEW

**Comment by Badiboy** [comment]
> No description provided.

May be it's time to do it?

**Comment by abdullaev388** [comment]
> > No description provided.
> 
> May be it's time to do it?

done

**Comment by Badiboy** [comment]
So, reviewed. 

For the main Telebot (not async).

1. No reasons for any modifications in telebot.utils. Please, restore all formatting: pep or not pep, no reason to do it now. 
2. Remove new methods and classes. Your idea is good, but not so fundamental to include in main code. This class can be placed in your example folder, it's enough. The one who like it can branch it from examples.

Examples are fine. Async Telebot should be agreed with @coder2020official .

**Comment by Badiboy** [comment]
Thanks. :)

**Comment by Badiboy** [comment]
image

Not needed any more.

**Comment by abdullaev388** [comment]
> image
> 
> Not needed any more.

Thanks. Removed.

**Comment by Badiboy** [comment]
Thanks. Async part will be reviewed tomorrow

**Review by coder2020official — APPROVED** [review]

**Pull request merged**
