### PR TITLE
HerokuPostGress Support

### PR DESCRIPTION
**Pull request by BLUE-DEVIL1134**
So, It The Database Support ..
when someone makes first bots he / she surely wants to add the names of the users into a place and for free

so they choose postgresql database of heroku...

By accepting this  PR You take a step towards advanced module and most probably worlds first telegram bot making module with inbuilt database features

**Special Fratures :**
* Allow A Freature Of Storinf The Chat Ids And Using Broadcast
* maximum users host in heroku of most will find this usefull
* This Is completly tested and bug free (oviously daily maintains are required)
* I have been using this for 3 months now without any errors

**Notice If PR Accecepted:**
_Add These Dependencies To The Setup.py file cause i couldnt find where to add_
* sqlalchemy
* pyscopg2

### CODE REVIEW

**Comment by Badiboy** [comment]
1. No glue to Heroku. It's simply uses Postgress backend. It's applicable (if it is working) to any Postgress.
2. No way for such class in init.py, it's for TeleBot and base supporting classes.
3. No reason to add such large dependencies to the main package.
4. Class has no reference to any other code. So no reason to place it to the existsing files.

If you want it to be added to the libary package - create a standalone file (like "handler_backends.py"), that can be optionally used (or not used) by library users. Provide (at least short) manual in the file. Create tests for it.

Make a sustainabe package. Creating new instance with a new functionality in the library is not just a "new class".

**Comment by Badiboy** [comment]
Naming is auful.
"HerokuPostgreSQL" - but it's the storage of users, not the base class for HerokuPostgress, and even for Heroku.
"class Database" - is a table for users storage.

`os.system('')`
What's that?

```
self.all_users.clear()
return self.all_users
```
?!?!

```
    def IsUser(self, chat_id):
        self.is_user(chat_id=chat_id)

    def AddUser(self, chat_id):
        self.add_user(chat_id=chat_id)

    def RemoveUser(self, chat_id):
        self.remove_user(chat_id=chat_id)
```
What for?!

```
    def GetAllUsers(self, chat_id):
        return self.get_all_users()
```
chat_id - what for?!

Did you read your code? Did you ever try to run anything with it?

It's not the first time you commit here the code which have no connection with a reality. Sorry, it's not possible to check them all the time. Next time your commits will be rejected "by default".

**Comment by BLUE-DEVIL1134** [comment]
> Naming is auful.
> "HerokuPostgreSQL" - but it's the storage of users, not the base class for HerokuPostgress, and even for Heroku.
> "class Database" - is a table for users storage.
> 
> `os.system('')`
> What's that?
> 
> ```
> self.all_users.clear()
> return self.all_users
> ```
> 
> ?!?!
> 
> ```
>     def IsUser(self, chat_id):
>         self.is_user(chat_id=chat_id)
> 
>     def AddUser(self, chat_id):
>         self.add_user(chat_id=chat_id)
> 
>     def RemoveUser(self, chat_id):
>         self.remove_user(chat_id=chat_id)
> ```
> 
> What for?!
> 
> ```
>     def GetAllUsers(self, chat_id):
>         return self.get_all_users()
> ```
> 
> chat_id - what for?!
> 
> Did you read your code? Did you ever try to run anything with it?
> 
> It's not the first time you commit here the code which have no connection with a reality. Sorry, it's not possible to check them all the time. Next time your commits will be rejected "by default".

You se the print statement, it prints in a warning yellow color so needs the `os.system` piece..

And second
```
self.all_users.clear()
return self.all_users
```
Each time called this function will clear the list and then again append them to the list then send

Third 
```
    def IsUser(self, chat_id):
        self.is_user(chat_id=chat_id)

    def AddUser(self, chat_id):
        self.add_user(chat_id=chat_id)

    def RemoveUser(self, chat_id):
        self.remove_user(chat_id=chat_id)
```

These Can Be Removed... (Really Sorry For This, I was learning node-js too at same time so add these for test.)

And Last
```
    def GetAllUsers(self, chat_id):
        return self.get_all_users()
```
The `chat_id` is not required, seems that i commited the test file..
In the next commit  i will add the changes that you said

**Comment by BLUE-DEVIL1134** [comment]
> 1. No glue to Heroku. It's simply uses Postgress backend. It's applicable (if it is working) to any Postgress.
> 2. No way for such class in init.py, it's for TeleBot and base supporting classes.
> 3. No reason to add such large dependencies to the main package.
> 4. Class has no reference to any other code. So no reason to place it to the existsing files.
> 
> If you want it to be added to the libary package - create a standalone file (like "handler_backends.py"), that can be optionally used (or not used) by library users. Provide (at least short) manual in the file. Create tests for it.
> 
> Make a sustainabe package. Creating new instance with a new functionality in the library is not just a "new class".

These changes might be ok
removed all unnecessary codes

**Pull request closed without merging**
