### PR TITLE
Update create_invite_link.py

### PR DESCRIPTION
**Pull request by DevAdvik**
Added .types while importing inline markup keyboards (fix)
Removed threading import since message is not to be deleted

### CODE REVIEW

**Comment by coder2020official** [comment]
Remove while true

**Comment by coder2020official** [comment]
You are basically putting while true in while true.

**Review by DevAdvik — COMMENTED** [review]
Removed while loop

**Comment by coder2020official** [comment]
Import both reply markups on the same line

**Review by DevAdvik — COMMENTED** [review]
Imported _both_ inline keyboards in same line

**Review by DevAdvik — COMMENTED** [review]
FINAL FIX

**Comment by coder2020official** [comment]
Another problem:
What about putting reply keyboard markup creation after imports? Creating reply markup for every user is a bad idea.

**Comment by coder2020official** [comment]
And i guess that's it.

**Comment by DevAdvik** [comment]
> What about putting reply keyboard markup creation after imports?
What does that mean? I don't get it:/
Like not importing markup keyboards at all?

**Comment by coder2020official** [comment]
image
This, before handlers, but after imports

**Comment by DevAdvik** [comment]
So like making `mrkplink` inline keyboard right after importing the module? That's neat, thanks!!

**Review by DevAdvik — COMMENTED** [review]
Assigned mrkplink right after importing markup keyboards

**Comment by Badiboy** [comment]
@coder2020official Put "approve" when it's ready to merge.

**Comment by coder2020official** [comment]
image
Move this line under markup creation as well.

**Comment by DevAdvik** [comment]
This cant be done I guess, the invitelink is created inside the newmember function, so url needs to be assigned there as well

**Comment by coder2020official** [comment]
Sorry for being innatentive.. I did not see that you were creating markup specially for user. So, InlineKeyboardMarkup creation should be in handler to avoid more buttons..

**Review by DevAdvik — COMMENTED** [review]
Done, added the InlineKeyboardMarkup exclusively in the function

**Review by coder2020official — APPROVED** [review]

**Pull request merged**
