### PR TITLE
Fixed filter class indexes

### PR DESCRIPTION
**Pull request by Aerodymier**

### CODE REVIEW

**Comment by Badiboy** [comment]
Any proofs that original code was incorrect and your update is correct?

**Comment by Aerodymier** [comment]
I was working on a new bot with this API wrapper, I wanted to do custom filters and I went with examples. Pylance wasn't previewing with first one but it previewed with removing the second index in the example. So I removed it and it works very well like that. I haven't tested the one in example but removing it made Pylance preview it + I had no problems.

**Comment by Aerodymier** [comment]
Note: I saw that if custom filter is registered by another script, others can use it with custom_filters.FilterName() so I was wrong and I'm closing this. I still don't know why Pylance doesn't preview like that.

**Comment by Badiboy** [comment]
> I haven't tested the one in example

Commiting to the public library without testing is a very bad practice...

**Comment by Aerodymier** [comment]
> > I haven't tested the one in example
> 
> Commiting to the public library without testing is a very bad practice...

Yeah.. I'm not experienced with public repos, please just ignore it. My bad.

**Pull request closed without merging**
