### PR TITLE
caption_entities in edit_message_caption

### PR DESCRIPTION
**Pull request by coder2020official**
https://github.com/eternnoir/pyTelegramBotAPI/issues/1247

### CODE REVIEW

**Comment by Badiboy** [comment]
Okay, you want to start participating in library dev. You implement some update, and lot of similar updates are already implemented. Why not to scroll the code and to see how such things should be done? 

image

**Comment by Badiboy** [comment]
You added the parameter to the method... And?....

**Comment by coder2020official** [comment]
Oops! Will commit later

**Comment by coder2020official** [comment]
Sorry

**Comment by coder2020official** [comment]
Done

**Pull request merged**
