### PR TITLE
Little code style improvement in service_utils

### PR DESCRIPTION
**Pull request by coder2020official**
## Description
Include changes, new features and etc:
- Added ImportError to block except to be more specific on errors related to pillow lib
- Removed io lib from try/except block since it is built-in lib

## Describe your tests
How did you test your change?

Python version:

OS:

## Checklist:
- [ ] I added/edited example on new feature/change (if exists)
- [ ] My changes won't break backward compatibility
- [ ] I made changes both for sync and async

### CODE REVIEW

**Comment by coder2020official** [comment]
@Tishka17

**Comment by coder2020official** [comment]
@Badiboy do you think it is worth releasing a new version with hotfix?

**Comment by Badiboy** [comment]
This cross-reference exists for months and appears in a very rare cases, so I do not think release of this update is urgent.

However, release an update is not a problem, if you think it's needed.

**Comment by Cub11k** [comment]
@coder2020official Same thing in StateRedisStorage, too broad except on redis import🕺

**Pull request merged**
