### PR TITLE
Black implementation test

### PR DESCRIPTION
**Pull request by coder2020official**
@Badiboy this is how approximately black looks like

### CODE REVIEW

**Comment by Badiboy** [comment]
I PERSONALLY don't like this type of formatting. 

image

It gives nothing valuable but lot of lines. It's just one file: you got 1400 lines for nothing. It's valuable for ones who are paid for lines of code :)

**Comment by coder2020official** [comment]
Idk, since you like changing formatting frequently, I thought you would like an automated system for that

**Comment by coder2020official** [comment]
I will see whether I can change something in settings though to avoid some of the changes

**Comment by Badiboy** [comment]
> Idk, since you like changing formatting frequently

I don't like ))) I just make some updates to formatting while making valuable updates ))

**Comment by coder2020official** [comment]
I just tried yapf with a style of facebook, here are some screenshots if you are interested:
image
image
image

This one is still similar to black in some ways, but there are differences. Thoughts? We still have to try to obey PEP-8?

**Comment by coder2020official** [comment]
We can technically ignore apihelper-like files(also asyncio_helper); Maybe in the future I will even try to get rid of these files due to a mess over there

**Comment by Badiboy** [comment]
May be just live things as is? 😂😂😂

**Comment by coder2020official** [comment]
Well, this is not my first time caring about PEP-8 - it is better if we at least try to follow it to some extent.

**Comment by Badiboy** [comment]
I'm not in favour of carry about anything "because of" - if that does not bring any value. I do not see what value black formatting brings except "now we hava black formatting"...

**Comment by coder2020official** [comment]
It indeed brings the value of cleaner code

**Comment by Badiboy** [comment]
"Cleaner code" is not a value. It's "cleaner code bacause of cleaner code".

**Comment by coder2020official** [comment]
Ok, if it does not harm project in any way - why not accept the new formatting?

**Comment by Badiboy** [comment]
"Add value" is the good reason of bring changes.
"Why not" is the bad reason of bring changes.

**Comment by coder2020official** [comment]
Well then I can argue that by improving formatting, we follow suggested PEP-8

**Comment by coder2020official** [comment]
And this is a better practise. The reason is "adding a value", not "why not"

**Comment by Badiboy** [comment]
"we follow suggested PEP-8" and it will give the project.... What? "Clear code"?

**Comment by Badiboy** [comment]
"this is a better practise" - do you follow all "better practices" in your life because these are better practices?

**Comment by coder2020official** [comment]
You should try to follow best practices as far as you can. They are created not for just existence but to help you understand your code faster

**Comment by Cub11k** [comment]
> I PERSONALLY don't like this type of formatting. 
> 
> image
> 
> It gives nothing valuable but lot of lines. It's just one file: you got 1400 lines for nothing. It's valuable for ones who are paid for lines of code :)

Consistency in the code formatting for better readability is kinda worth it, provided no one really cares about the number of lines and the size of the py-files (at least in my opinion)

**Pull request closed without merging**
