### PR TITLE
raise other exceptions in antiflood function

### PR DESCRIPTION
**Pull request by S1RANN**
Other kinds of errors like `Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified` during sending a set of photos or `urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme 127.0.0.1` for forgetting the 'http:\\\\' may occur and should raise exceptions.

### CODE REVIEW

**Comment by coder2020official** [comment]
Hi!
I'll investigate it and review ASAP. Thank you for pull request.

**Comment by S1RANN** [comment]
For unknown reasons from telegram server, it's likely to receive `400` error if you try to send a photo via a valid HTTP URL. Strangely, appending random query strings (like `&random=1`) to the URL may fix the problem though. If this happens in the process of send groups of photos then some of which will be lost. Since the code only catch `429` error, no information about that will be logged. It took me a while to find out the photos I received are not complete.
Here is an example:
```Python
photo_url = 'https://lh3.googleusercontent.com/hV30wubtbC07_JJpyWaVxSdFo59gWb6MZxcoWd-v2oM_XPubK5Xv9u0Zpt6fDj8RIUUGLMVSSKnIILBwusgHarhs7iTFglggogaS0e1PVrcapA_1jStVNZH8LgwtsA9shvJGdjPcj4pz4ODvpKlFwaEdz8u9sAuQyUEZmD96iTSnvyj0LDmsQMQy9kf2Y0pwu8ZHUTadJ8RigiTOYIGpwapu6qWoU5pBVgSxdqiuXUoo-vqP9YHFzPo4qAxB4GWbsrfDLxe-l1F4clCGhJeNp30S_SQStKkPR1efdgGRi92oNLwnR7dF8VUjwYmRbqro3szeY_zPhEu3dZjzTjyq9uf62T2W0PrIwSB8-RmLgdyYBf674gSIyCZd6eeE2-tHLKc20NXV-HMTy7kf6L_5dy9tunxCVZa0Z13a5MRyLfQEaFqDhjb8M7DGaEfe0PI1hhv3HNWDs1BlcvIgdBV-t5sLRXFH6sujRhAs7iC6R8cwW3STL-UIL-5WQZOvmttZaAKWMreFqAQ9Up2m-3TeK3EcgNrn1wg-FhyWfEOGa2REetJ5hZU776QO_TuxLd7vrcFZ1a_y5C5eYyUBi--184RmqdEeXx39qcfYMmuj3w=w1916-h1436-no'

antiflood(bot.send_photo, chat_id=USER_ID, photo=photo_url) # No error logged
bot.send_photo(chat_id=USER_ID, photo=photo_url) # Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
```

**Comment by Badiboy** [comment]
@S1RANN 
Add 
`return msg`
To the end of the function.

**Comment by coder2020official** [comment]
I've asked @barbax7 to take a look, so let's wait for him as well

**Comment by barbax7** [comment]
I'm here, looking at it

**Review by barbax7 — APPROVED** [review]
it seems perfect, thank you

**Comment by Badiboy** [comment]
👍

**Pull request merged**
