### PR TITLE
add example of a link to a template

### PR DESCRIPTION
**Pull request by Codwizer**
## Description
Include changes, new features and etc:

## Describe your tests
How did you test your change?

Python version:

OS:

## Checklist:
- [ ] I added/edited example on new feature/change (if exists)
- [ ] My changes won't break backward compatibility
- [ ] I made changes both for sync and async

### CODE REVIEW

**Comment by coder2020official** [comment]
I think it would look better if you pasted your template link right away

**Comment by Badiboy** [comment]
Don't look useful.

**Comment by Codwizer** [comment]
Why is that? it is convenient to go to my repository and find the template that you need than to search all over the Internet yourself and yes, I will slowly add new ones00:23, 3 апреля 2024 г., Badiboy ***@***.***>:
Don't look useful.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by Badiboy** [comment]
Advert of your repository is not the purpose of readme.

Also links from official documentation to repositories not controlled by maintainers is not acceptable.

**Pull request closed without merging**
