### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by coder2020official**
I added some useful methods. I wanted to separate handlers in other files. But, there was no method to add handler. In order to add handler, I needed to build dict from handler, then use add handler method. I created special methods for it, now, you just create a function with message attribute, and register it.

Screen Shot 2021-08-16 at 22 44 34

What do you think of this change? It would make easier to separate handlers in other files and call them, after register.

### CODE REVIEW

**Comment by coder2020official** [comment]
If you accept this PR and testing, you could release a new version. What do you think?

**Comment by Badiboy** [comment]
There is no problem in releasing new version nearly any time :)

**Comment by coder2020official** [comment]
Ok, i will wait :)

**Comment by Badiboy** [comment]
@coder2020official As far as I got - it's the "dynamic" alternative to static handlers adding?
```
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
```
If so - why not: more alternatives - more flexible tool :)

**Comment by coder2020official** [comment]
Yes, it will help to register handlers from another files too.

**Pull request merged**
