### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fcoagz**

### CODE REVIEW

**Comment by Badiboy** [comment]
To the top? Mmmm... You really think your bot is so brilliant to go to top in front of all others?

**Comment by fcoagz** [comment]
Sorry, I really didn't think of that. just look for the section to add it

**Comment by Badiboy** [comment]
The list is incremental. Just move it to bottom.

**Comment by fcoagz** [comment]
I already edited it: 3. it's not at the top

**Pull request merged**
