### PR TITLE
Added `WebApp` functions

### PR DESCRIPTION
**Pull request by TECH-SAVVY-GUY**
`validate_WebApp_data()` - Use to validate the data received by the WebApp from Telegram.

`parse_WebApp_data()` - Use to parse the data sent to the WebApp from the bot's backend.

### CODE REVIEW

**Comment by Badiboy** [comment]
What for?

How it can and will be used?

Usage examples?

Any additional comments?

**Comment by TECH-SAVVY-GUY** [comment]
**_[https://core.telegram.org/bots/webapps#validating-data-received-via-the-web-app](https://core.telegram.org/bots/webapps#validating-data-received-via-the-web-app)_**

**Comment by TECH-SAVVY-GUY** [comment]
I will be adding examples for WebApp implementations using the library soon.

**Comment by Badiboy** [comment]
> I will be adding examples for WebApp implementations using the library soon.

Thank you.

Could you please adjust function name case to pythonic style used here (https://github.com/eternnoir/pyTelegramBotAPI/blob/6b19d631d19edf35a7ba68139aad6d08df2a2217/telebot/apihelper.py#L1619)?
validate_web_app_data()
parse_web_app_data()

**Comment by TECH-SAVVY-GUY** [comment]
Done 👍🏻

**Pull request merged**
