### PR TITLE
new 5.3 function names

### PR DESCRIPTION
**Pull request by SwissCorePy**
added the new function names (the previous names are still working) from 5.3 and some other small changes

### CODE REVIEW

**Comment by Badiboy** [comment]
image
I propose to
1. remove apihelper.get_chat_members_count and kick_chat_member 
2. remove getChatMembersCount and kickChatMember from class description
2. Map TeleBot,get_chat_members_count to TeleBot.get_chat_member_count and Telebot.kick_chat_member to TeleBot.ban_chat_member. Map means call one from another respectively
3. Add logger.info('get_chat_members_count is deprecated') and logger.info('kick_chat_member is deprecated') to these functions. And a month later change it to warning. :)

What do you think about it?

**Comment by SwissCorePy** [comment]
> image
> I propose to
> 
>     1. remove apihelper.get_chat_members_count and kick_chat_member
> 
>     2. remove getChatMembersCount and kickChatMember from class description
> 
>     3. Map TeleBot,get_chat_members_count to TeleBot.get_chat_member_count and Telebot.kick_chat_member to TeleBot.ban_chat_member. Map means call one from another respectively
> 
>     4. Add logger.info('get_chat_members_count is deprecated') and logger.info('kick_chat_member is deprecated') to these functions. And a month later change it to warning. :)
> 
> 
> What do you think about it?

Yes this makes sense :) 
I'll change that

**Comment by SwissCorePy** [comment]
couldn't we use the util.depricated_decorator instead?

**Comment by Badiboy** [comment]
> couldn't we use the util.depricated decorator instead?

I made this method but never used it. There were some reasons for it but they had gone. 
I didn't use it and not sure about how it work. :))))))))

**Comment by SwissCorePy** [comment]
> > couldn't we use the util.depricated decorator instead?
> 
> I made this method long ago but never used it. There were some reasons for it but they had gone.
> I didn't use it and not sure about how it work. :))))))))

Haha ok ^^ maybe mark the depricated decorator as depricated too xD

**Pull request merged**
