### PR TITLE
add PollAnswer, poll_answer_handler

### PR DESCRIPTION
**Pull request by drforse**
+ add PollAnswer, poll_answer_handler
+ make User Serializable and Dictionaryble
+ some pep fixes

### CODE REVIEW

**Comment by Badiboy** [comment]
Thank you. 

Need clarification:

1. 
```
PollAnswer.to_json
PollAnswer.to_dict
```
what for these methods are created? They are never used.

2. 
```
User.to_json
User.to_dict
```
what for these methods are added?
First is never used.
Second is used in the above methods that are never used.

**Comment by drforse** [comment]
These methods may be used by library users for storing and viewing data

**Comment by Badiboy** [comment]
https://travis-ci.org/github/eternnoir/pyTelegramBotAPI/jobs/685904593

Test failed. Please, fix ASAP.

**Comment by drforse** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/840

**Pull request merged**
