### PR TITLE
Added class ChatMemberUpdated

### PR DESCRIPTION
**Pull request by SwissCorePy**
* Added class `ChatMemberUpdated` to `types.py`
* Simplified `de_json` functions in `WebhookInfo` and `Update` classes (for overall more consistent code)
* changed `options_ids` to `option_ids` in class `PollAnswer`
* Added test for `ChatMemberUpdated` class in `test_types.py` and added the fields `my_chat_member` and `chat_member` to `Update` class and its tests

My last PR for today, i promise ^^

### CODE REVIEW

**Comment by Badiboy** [comment]
image

Not suitable update without default parameters values ("None") in __init_.

**Comment by Badiboy** [comment]
image

Frankly speaking, this update does not look reasonable. All _init_ parameters are mandatory, you simply put parameters into dict and later unroll dict to parameters... In spite of all other updates, this one looks a bit confusing instead of being more clear and code reduction...

**Comment by Badiboy** [comment]
It's not a key point, just some subjective oppinion for the next PR...

**Comment by SwissCorePy** [comment]
> image
> 
> Frankly speaking, this update does not look reasonable. All _init_ parameters are mandatory, you simply put parameters into dict and later unroll dict to parameters... In spite of all other updates, this one looks a bit confusing instead of being more clear and code reduction...

I know this change is little bit pointless in that class. I did it just for consistency. But why not just modify the dict and pass that to _init_ instead of store all the values in new variables and pass them in the correct order. I like the dict method more. But if you wish i can change it back :)

**Pull request merged**
