### PR TITLE
Post-huge update fix #1

### LINKED ISSUE #1: Add max cache message size.

### PR DESCRIPTION
**Pull request by Badiboy**
## Description
Adopt new class loading from json to common manner + bugfixes

### CODE REVIEW

**Comment by Badiboy** [comment]
@coder2020official Version of aiohttp in requirements do not support Python 3.12: https://github.com/eternnoir/pyTelegramBotAPI/actions/runs/7398167287/job/20126753707?pr=2109

Will we try to raise aiohttp or currently left Python 3.12 officially not supported?

**Comment by coder2020official** [comment]
FUCK
I'll take a look, wait a sec

**Comment by Badiboy** [comment]
@coder2020official It's not a big problem and not too urgent: we can wait with adding ython 3.12. It's just a proposal.

**Comment by coder2020official** [comment]
The pull request overall looks good to me.
I think we have to wait for some time until we add python 3.12 support. I see that new versions of aiohttp support it, and I will just have to go through deprecated things and make sure it will all work. For now just remove 3.12

**Comment by coder2020official** [comment]
One more question - for bot api update, did you implement the thing i did not:
Improved documentation for the field message of the class [callbackQuery](https://core.telegram.org/bots/api#callbackquery) and the field pinned_message of the class [Message](https://core.telegram.org/bots/api#message) by adding the classes [MaybeInaccessibleMessage](https://core.telegram.org/bots/api#maybeinaccessiblemessage) and [InaccessibleMessage](https://core.telegram.org/bots/api#inaccessiblemessage).

**Comment by Badiboy** [comment]
> One more question - for bot api update, did you implement the thing i did not:

Not yet.

**Comment by coder2020official** [comment]
When are you planning to do so? Any ideas on that though? And will you release now or after implementing it

**Comment by Badiboy** [comment]
Firstly I plan to fix things of big update. I have a list of fixes on the field of deprecation.

The update is far from being ready to release IMHO.

**Pull request merged**
