### PR TITLE
hide token from debug logs

### PR DESCRIPTION
**Pull request by ModischFabrications**
Prevent leaks of the bot token by hiding it from the log, learned it the hard way during https://github.com/eternnoir/pyTelegramBotAPI/issues/1058.

### CODE REVIEW

**Comment by Badiboy** [comment]
Seems too conservative: you may run several bots in one code, so you need to identify them.

I propose to remove the part of token after ":". So you will see bot ID and identify bot, bot not publish token. It's a bit more complex, but seems more convenient. 

_PS. Do not forget that bot id has not fixed length..._

**Comment by ModischFabrications** [comment]
> several bots

good point, I wasn't aware of that. This will still leak bot ids, which might be unwanted for private bot users that rely on "security by obscurity", but I guess it's the lesser evil. Will be done in a moment...

**Comment by p1ner0** [comment]
.env solves the issue :+1: 

```
import environs

env = environs.Env()
env.read_env('.env')

BOT_TOKEN = env('API_KEY')
```

**Comment by p1ner0** [comment]
storing the API_KEY in a external .env file

**Pull request merged**
