### PR TITLE
Add webapp example

### PR DESCRIPTION
**Pull request by nypava**
## Description
Simple webapp example

### CODE REVIEW

**Comment by coder2020official** [comment]
That's too simple...

**Comment by nypava** [comment]
IG it is pretty enough as an example.

**Comment by Badiboy** [comment]
> IG it is pretty enough as an example

If library mainteinter says that something is wrong it's better to take it into account.

**Comment by coder2020official** [comment]
@badiboy did you turn off notifications for my states PR or are you in process of review? I got no comment saying it is in the review, so I hope you have seen it

**Comment by nypava** [comment]
> > IG it is pretty enough as an example
> 
> If library mainteinter says that something is wrong it's better to take it into account.

I wasn't being stubborn. I was simply stating my opinion on why it is simple, so that he could further explain his point.

**Comment by coder2020official** [comment]
Maybe you could improve your example in some ways; Use @asmico_attach_bot as an example, try to expand the functionality to show some basic yet useful thing in webapp

**Comment by nypava** [comment]
Sure, I will add some features. My intention was to show how to implement a webapp using pytelegrambotapi, rather than to showcase the functionality of webapp it self.

**Comment by coder2020official** [comment]
Well, anyone can implement a mini app using code, and simply changing link to google.com 
Still a mini app :)

**Comment by nypava** [comment]
@coder2020official what about now?

**Comment by coder2020official** [comment]
Thanks, that is a really good example. 
A few things before merging:
- Rename Web App to Mini App(mini_app folder, texts, etc)
- Create an example for async, write a comment at the top saying sources of website are at examples/mini_app

**Comment by nypava** [comment]
> * Create an example for async, write a comment at the top saying sources of website are at examples/mini_app

As I am going add async support is it fine to use this structure?  (rather than duplicating web file twice)

examples/
├─ mini_app_web/
│  ├─ index.html
│  ├─ script.js
│  ├─ style.css
├─ asynchronous_telebot/
│  ├─ mini_app.py
├─ mini_app.py

**Comment by coder2020official** [comment]
yep sounds good to me, no need for duplicating
just don't forget to leave comments telling abt this

**Comment by coder2020official** [comment]
LGTM. @Badiboy ?

**Comment by Badiboy** [comment]
👍

**Pull request merged**
