### PR TITLE
Changes from review of bot api 6.6

### PR DESCRIPTION
**Pull request by coder2020official**

### CODE REVIEW

**Comment by coder2020official** [comment]
@Badiboy i'm not sure about changes. Review was so messy and i could skip smth, can you review it?

**Comment by coder2020official** [comment]
It would be better if you suggest changes next time(so i could directly commit those changes)

**Review by Badiboy — APPROVED** [review]

**Comment by coder2020official** [comment]
Are you sure this time?

**Comment by Badiboy** [comment]
Mess - yes. They are not full but looks correct.

**Comment by coder2020official** [comment]
@Badiboy anything left? Or is it ready?

**Comment by Badiboy** [comment]
I don't know. I need to re-check all 26 review requests. I will when I find time for this.

**Pull request merged**
