### PR TITLE
Custom filters

### PR DESCRIPTION
**Pull request by coder2020official**
Added new feature - from now you can create your own custom filters.
Here are some examples of how to use it.
image

You can make any check you want. Class should have .check() method, and should have message attribute.
Message update passes to your custom filter, and it runs your filter's check method.

### CODE REVIEW

**Comment by coder2020official** [comment]
@SwissCorePy @Badiboy What do you think

**Comment by Badiboy** [comment]
image

**Comment by Badiboy** [comment]
```
                if message_filter in self.custom_filters:
                    filter_check = self.custom_filters.get(message_filter)
```
If you already checked, that message_filter is in - you can use []. And less boilerplate code...

```
        elif message_filter == 'func':
            return filter_value(message)
        elif self.custom_filters and message_filter in self.custom_filters:
            filter_check = self.custom_filters[message_filter]
            return filter_value == filter_check.check(message)
        else:
            return False

```

**Comment by Badiboy** [comment]
Function create_filter 
1. No creates but adds
2. not filter but custom filter
Wheat about 
**add_custom_filter**?
(Just for discussion)?

**Comment by coder2020official** [comment]
Hm, i think this sounds better :)

**Comment by coder2020official** [comment]
image

**Comment by SwissCorePy** [comment]
I dont think this is a good idea. because the bot has to do a getChatMember request after every update causing to slow down the bot.

**Comment by coder2020official** [comment]
This is custom filter. Of course it should make request. This is just an example, you can make any filter.

It is exactly the same as any other filter, like let's say content_types.

It checks every time whether content_type is in list of content_types.

I will show another example.

**Comment by coder2020official** [comment]
image

**Comment by coder2020official** [comment]
You can implement any filter for anything - it passes message to your check method. And you perform any check :)

**Comment by Badiboy** [comment]
> I dont think this is a good idea. because the bot has to do a getChatMember request after every update causing to slow down the bot.

This is an example. Responsibility is on filter creator :)

**Comment by SwissCorePy** [comment]
The idea of custom filters is ok. 

but i think the bot should not do requests in the background. (except getting updates)
wouldn't  a custom_message_handler be a better idea?

But im fine with it if you both like it this way :)

**Comment by Badiboy** [comment]
> but i think the bot should not do requests in the background. (except getting updates)

Bro, this example has nothing with proposed update. Just check "Files changed", not the give screens.

**Comment by SwissCorePy** [comment]
Sorry ^^
I think i would never use this feature but i like the idea. :)

**Comment by coder2020official** [comment]
image
Before, it was accepting bool only. Now, i allowed another parameter

**Comment by coder2020official** [comment]
*names of parameters in check method can change. Try to test

**Pull request merged**
