### PR TITLE
caption as first keyword argument (when it exists)

### PR DESCRIPTION
**Pull request by fgallaire**
For a most consistent argument order

### CODE REVIEW

**Comment by Badiboy** [comment]
Impossible to change function signatures: it breaks backward compatibility for existing projects. :(

You may be right: it looks more reasonable, but...

_PS: I do not know if it's a good Python practice to pass named parameters in a raw..._

**Comment by fgallaire** [comment]
Warning for API update in changelog:  possible backward compatibility issues

**Comment by Badiboy** [comment]
For me it's a **very weak** reason to make **lot of problems** to lot of library users.

**Comment by EskiSlav** [comment]
Fully agree with **Badiboy**, because my own projects should be rewritten if these changes applied and many thousands of projects too

**Pull request closed without merging**
