### PR TITLE
Create a template for QWERTY custom keyboard an example for ReplyKeyboardMarkup

### PR DESCRIPTION
**Pull request by zeph1997**
Created a template for QWERTY custom keyboard that can be used by users for their own use cases.
This is an example created using ReplyKeyboardMarkup.

### CODE REVIEW

**Comment by Badiboy** [comment]
Please, provide screenshots how it looks like.

**Comment by Badiboy** [comment]
`markup.add(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9])`
Better
`markup.add(*row)`

**Comment by zeph1997** [comment]
Screenshot of Custom Keyboard
ReplyKeyboardMarkup

**Comment by zeph1997** [comment]
> `markup.add(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9])` Better `markup.add(*row)`

Thanks for this, will modify to your solution

**Comment by zeph1997** [comment]
Modified 
`markup.add(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9])` to `markup.add(*row)`

**Comment by Badiboy** [comment]
Thanks.

**Pull request merged**
