### PR TITLE
Add @bot.poll_handler to be notified of new poll states

### PR DESCRIPTION
**Pull request by Tkachov**
Pretty straight-forward edits, implemented similarly to other handlers. Updated `types.Poll` so it stores all fields passed by Telegram.

Can be used similar to other handlers:
```
@bot.poll_handler(func=lambda call: True)
def handle_vote(poll):
	print poll
```

Didn't update README and didn't write any tests/examples.

### CODE REVIEW

**Comment by Badiboy** [comment]
Hi. Is it tested on some running bots?

**Comment by Tkachov** [comment]
Of course. I've tested it on a test bot though, it just was printing `poll` object so I could see it gets the right data.

**Comment by Tkachov** [comment]
If you want to test it a little bit, you can try adding `@pyTelegramBotAPI_test_bot` to a group and using `/poll` command. It creates a poll and then posts a message every time it `@bot.poll_handler` is notified. I'll keep this bot working for a day or two.

**Comment by Badiboy** [comment]
It's a bad practice, but no time currently for this. :( Let's wait for a feedback from users.

**Pull request merged**
