### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by SwissCorePy**
* Fixed type warnings in some editors by changing `var: Type = None` to `var: Union[Type, None] = None`
* changed some args from `obj['arg']` to `obj.get('arg')` if arg is optional
* better PEP-8 compliance for less weak warnings
* added tests for the new type `ChatInviteLink`

I hope the type warnings are gone for you too

### CODE REVIEW

**Comment by Badiboy** [comment]
image
But why?

**Comment by Badiboy** [comment]
image
Location in Venue is not optional:
https://core.telegram.org/bots/api#venue

**Comment by Badiboy** [comment]
image
photos in UserProfilePhotos also is not optional:
https://core.telegram.org/bots/api#userprofilephotos

**Comment by SwissCorePy** [comment]
> image
> But why?

I thougt its not really necessary to make typehints for functions that only got called internally. i thougt i remove them for now.

**Comment by Badiboy** [comment]
> I thougt its not really necessary to make typehints for functions that only got called internally. i thougt i remove them for now.

Ook

**Comment by SwissCorePy** [comment]
> image
> photos in UserProfilePhotos also is not optional:
> https://core.telegram.org/bots/api#userprofilephotos

I know, but i dont know what happens if a user has no profile pictures. i thougt a short check can not hurt :)

**Comment by SwissCorePy** [comment]
> image
> Location in Venue is not optional:
> https://core.telegram.org/bots/api#venue

ok, this is really not not necessairy.. my bad

**Comment by Badiboy** [comment]
image
You seems right, really very strange contruction... "pop" replace correct naming to incorrect one... I think everything should be renamed to option_ids according to https://core.telegram.org/bots/api#polloption, without any "pop"s.

**Comment by Badiboy** [comment]
The remaining updates looks fine, thank you. 

Should I merge this and you will fix updated in new one, or you will update this one?

**Comment by SwissCorePy** [comment]
> image
> You seems right, really very strange contruction... "pop" replace correct naming to incorrect one... I think everything should be renamed to option_ids according to https://core.telegram.org/bots/api#polloption, without any "pop"s.

Yea I thougt i do not touch that for now for beckwards compatibility. so i just left a comment. the pop is to avoid passing unused vars

**Comment by SwissCorePy** [comment]
> The remaining updates looks fine, thank you.
> 
> Should I merge this and you will fix updated in new one, or you will update this one?

I will fix that in a new one. should i change the `option_ids` to the correct name too?

**Comment by Badiboy** [comment]
> Yea I thougt i do not touch that for now for beckwards compatibility. so i just left a comment. the pop is to avoid passing unused vars

I think it's definitely will not work anyway, because it passes to json "options_ids":
 'options_ids': self.options_ids}
which will not be recognized by Telegram. So there is no compatibility which we can keep :)

**Comment by Badiboy** [comment]
> I will fix that in a new one. should i change the `option_ids` to the correct name too?

But "option_ids" is the correct naming:
https://core.telegram.org/bots/api#polloption
I do not understand what you are talking about.

**Comment by SwissCorePy** [comment]
> > I will fix that in a new one. should i change the `option_ids` to the correct name too?
> 
> But "option_ids" is the correct naming:
> https://core.telegram.org/bots/api#polloption
> I do not understand what you are talking about.

Yea you are right. I meant if someone tries to get polloption.options_ids in his code it will not work in the future. but i'll fix that

**Comment by Badiboy** [comment]
> Yea you are right. I meant if someone tries to get polloption.options_ids in his code it will not work in the future. but i'll fix that

Yes, it will not. But this code will not work anyway :)

**Pull request merged**
