### PR TITLE
CallbackData class added

### PR DESCRIPTION
**Pull request by abdullaev388**

### CODE REVIEW

**Comment by coder2020official** [comment]
Token 👀

**Comment by coder2020official** [comment]
Are you sure creating a separate file for this is ok? I think it would be better to implement it in util file.

**Comment by Badiboy** [comment]
> Are you sure creating a separate file for this is ok? I think it would be better to implement it in util file.

Why not. The same as states. :)
PS. I'll check later what's that.

**Comment by coder2020official** [comment]
> > Are you sure creating a separate file for this is ok? I think it would be better to implement it in util file.
> 
> Why not. The same as states. :) PS. I'll check later what's that.

You mean custom filters :)

**Review by coder2020official — CHANGES_REQUESTED** [review]
It would be good to have more description on classes and their methods. Just add parameters overview.
I have tested it, great job!

**Review by coder2020official — APPROVED** [review]

**Pull request merged**
