### PR TITLE
Fix traceback exeptions

### PR DESCRIPTION
**Pull request by dannkunt**
logger.debug is only for debugging telebot, but we need to fix bugs in our bots, so this will help

### CODE REVIEW

**Comment by Badiboy** [comment]
> logger.debug is only for debugging telebot, but we need to fix bugs in our bots, so this will help

Here you wil get lot of "ordinal" errors: connection issues, API issues etc. So log of all users will be overflooded with errors.
1. This exception will be raised to the "polling" method and then raised there. So you can catch this exception when you call polling. If you use infinite_polling, the raised exception will be logged as "logger.error" there, so you will see it in log.
2. You can use bot.exception_handler to bind your own exception handling routine and log there whatever you want.

**Comment by dannkunt** [comment]
1. No, I always use bot.infinity_polling(3600, True) but there is no good exceptions
It catshes this:

`2021-01-30 11:12:38,587 (__init__.py:515 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found"`

instead of this:

`2021-01-30 11:11:47,616 (util.py:75 WorkerThread1) ERROR - TeleBot: "ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found',)
Traceback (most recent call last):
  File "/run/media/dannkunt/01D67E9E24F55A00/Programing/Python/venvs/linux/bef_music_bot39_venv/lib/python3.9/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "/run/media/dannkunt/01D67E9E24F55A00/Programing/Python/bef_music_bot/tele_bot.py", line 299, in upc_1
    bot.send_message("stuf", 12312)
  File "/run/media/dannkunt/01D67E9E24F55A00/Programing/Python/venvs/linux/bef_music_bot39_venv/lib/python3.9/site-packages/telebot/__init__.py", line 739, in send_message
    apihelper.send_message(self.token, chat_id, text, disable_web_page_preview, reply_to_message_id,
  File "/run/media/dannkunt/01D67E9E24F55A00/Programing/Python/venvs/linux/bef_music_bot39_venv/lib/python3.9/site-packages/telebot/apihelper.py", line 225, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/run/media/dannkunt/01D67E9E24F55A00/Programing/Python/venvs/linux/bef_music_bot39_venv/lib/python3.9/site-packages/telebot/apihelper.py", line 132, in _make_request
    json_result = _check_result(method_name, result)
  File "/run/media/dannkunt/01D67E9E24F55A00/Programing/Python/venvs/linux/bef_music_bot39_venv/lib/python3.9/site-packages/telebot/apihelper.py", line 159, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
"`
2. There is no documentation for bot.exception_handler

**Comment by Badiboy** [comment]
1. In infininty_polling the trace log is also under debug level. I got your request, I think it will be better to have adjustable parameter in infininty_polling.

2. Yes. You need to create a derrived class of ExceptionHandler, implement "handle" method and pass it to the exception_handler parameter of Telebot constructor or manually assignt to the field exception_handler of TeleBot instance.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1090
Will this solve your needs?

**Pull request closed without merging**
