### PR TITLE
new deprecated decorator

### PR DESCRIPTION
**Pull request by SwissCorePy**
I think this could be useful in the future :) 
Or should we replace the old deprecated decorator?
what du you think?

### CODE REVIEW

**Comment by Badiboy** [comment]
I propose simply replace the old "deprecated" one. I definitly sure nobody used it.

And better to add some tests for it.

**Comment by SwissCorePy** [comment]
ok :)

**Comment by SwissCorePy** [comment]
hope this test is ok and work

**Comment by Badiboy** [comment]
Super, thank you.

> hope this test is ok and work
I hope too. I did not see anyhing in output, hope it means it works. :)

**Comment by SwissCorePy** [comment]
> Super, thank you.
> 
> > hope this test is ok and work
> 
> I hope too. I did not see anyhing in output, hope it means it works. :)

the should not be any output. just a message in the logs. but i dont know where the logs are stored to be honest ^^

**Comment by SwissCorePy** [comment]
But i did a test with printing and it works fine :)

**Pull request merged**
