### PR TITLE
Bot API 5.0 pinning-unpinning logic update

### PR DESCRIPTION
**Pull request by alexmechanic**
+ add unpin_all_chat_messages() (former unpin_chat_message())
* update unpin_chat_message() (add message_id arg)

### CODE REVIEW

**Comment by Badiboy** [comment]
image

**Comment by Badiboy** [comment]
image

message_id is optional. Should have default value (None) for backward compatibility.

**Comment by alexmechanic** [comment]
Fair point

**Comment by Badiboy** [comment]
image

And what about this? Should I say obviously, that this parameter IS NOT USED in the function?

**Pull request merged**
