### PR TITLE
added examples of multibot

### PR DESCRIPTION
**Pull request by abdullaev388**
Examples of multibot (sync and async)

### CODE REVIEW

**Review by coder2020official — CHANGES_REQUESTED** [review]
Well done!
Just one thing: is it good to create a new instance for each new webhook request?
image

**Comment by abdullaev388** [comment]
> 

it is not good, but this example is supposed to be as simple as possible.
it can be upgraded. For example instead of saving True as a value of token, the bot instance can be saved there like:
tokens = {}
tokens['token'] = TeleBot()
and then retreived whenever update comes. But anything like that users should implement by themselves

**Comment by coder2020official** [comment]
Let's wait for badiboy's response

**Comment by Badiboy** [comment]
We discussed and desided that for your case (multibots) it's fine. Thanks. :)

**Pull request merged**
