### PR TITLE
add default None for get_my_commands, examples for bot.set_my_commands

### PR DESCRIPTION
**Pull request by artyl**
Add default parameters for call bot.get_my_commands() instead bot.get_my_commands(scope=None, language_code=None)
Add examples for [issues #1414  set_my_commands problem](https://github.com/eternnoir/pyTelegramBotAPI/issues/1414 )

### CODE REVIEW

**Comment by coder2020official** [comment]
Why did you import os?

**Comment by artyl** [comment]
I forgot to delete it. I used it in the line where I read the secrets, which I deleted in the release.

**Comment by Badiboy** [comment]
Thank you.

Please, update os import and we'll merge it.

**Comment by artyl** [comment]
> Please, update os import and we'll merge it.
I remove unused os import in this files and previous timer_bot.py examples

**Comment by Badiboy** [comment]
👌

**Pull request merged**
