### PR TITLE
Update types.py

### PR DESCRIPTION
**Pull request by iPurya**
Sending stickers everytime have different file_id, so for detecting special stickers we need a unique parameter.

### CODE REVIEW

**Comment by Badiboy** [comment]
Please, fix tests also.

https://travis-ci.org/github/eternnoir/pyTelegramBotAPI/jobs/705556956

**Comment by iPurya** [comment]
It's been a while telegram gives stickers a unique file id and these tests is for before that.

I think this update will be work well.

**Comment by Badiboy** [comment]
I do not ask why tests fails: I know why they fails.

Your update currently brakes commit build test, because code tests are not updated to new required parameter.

So please update code tests also so we'll have successfull build test.

**Comment by iPurya** [comment]
test codes updated.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/908/files

I do not see any changes here.

**Comment by Badiboy** [comment]
I'm not sure that your patch will be aplied, but let's try...

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/tests/test_types.py

It is not. So please, make a separate update for tests.

**Pull request merged**
