### PR TITLE
A Google Cloud Functions webhook

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by fgallaire** [comment]
I use this code in many bots now and I would like to avoid repast it again and again

**Comment by Badiboy** [comment]
1. How do you use it? Can you please provide sample code?

2. Why you mentioned this as Google Functions in commit and code comment? I see no relations with google in the provided update.

**Review by BLUE-DEVIL1134 — APPROVED** [review]

**Comment by fgallaire** [comment]
>     1. How do you use it? Can you please provide sample code?

I need to do some more tests before merging

>     2. Why you mentioned this as Google Functions in commit and code comment? I see no relations with google in the provided update.

Yes it's Google Cloud Functions specific code (which use implicit Flask import).

**Comment by Badiboy** [comment]
Patch is finalized?

**Review by BLUE-DEVIL1134 — APPROVED** [review]

**Comment by BLUE-DEVIL1134** [comment]
@Badiboy , Its Finalized As Much As I See.

**Comment by fgallaire** [comment]
@BLUE-DEVIL1134 @Badiboy I have a little problem to fix

**Pull request closed without merging**
