### PR TITLE
Bot API 6.7 - Not much to do, just minor improvements

### PR DESCRIPTION
**Pull request by coder2020official**
- [x] Added support for launching [Web Apps](https://core.telegram.org/bots/webapps) from inline query results by replacing the parameters switch_pm_text and switch_pm_parameter of the method [answerInlineQuery](https://core.telegram.org/bots/api#answerinlinequery) with the parameter button of type [InlineQueryResultsButton](https://core.telegram.org/bots/api#inlinequeryresultsbutton).
- [x] Added the field web_app_name to the class [WriteAccessAllowed](https://core.telegram.org/bots/api#writeaccessallowed).
- [x] Added the field switch_inline_query_chosen_chat of the type [SwitchInlineQueryChosenChat](https://core.telegram.org/bots/api#switchinlinequerychosenchat) to the class [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton), which allows bots to switch to inline mode in a chosen chat of the given type.
- [x] Added the field via_chat_folder_invite_link to the class [ChatMemberUpdated](https://core.telegram.org/bots/api#chatmemberupdated).
- [x] Added the ability to set different bot names for different user languages using the method [setMyName](https://core.telegram.org/bots/api#setmyname).
- [x] Added the ability to get the current bot name in the given language as the class [BotName](https://core.telegram.org/bots/api#botname) using the method [getMyName](https://core.telegram.org/bots/api#getmyname).
- [x] Added the ability to change bot settings from the bot's profile in official Telegram apps, including the ability to set animated profile photos.
- [x] Added the ability to specify custom emoji entities using [HTML](https://core.telegram.org/bots/api#html-style) and [MarkdownV2](https://core.telegram.org/bots/api#markdownv2-style) formatting options for bots that purchased additional usernames on [Fragment](https://fragment.com/).

### CODE REVIEW

**Comment by coder2020official** [comment]
image
*Skipping for now*

**Comment by coder2020official** [comment]
Skipping last one. While implementing found a bug.

**Comment by coder2020official** [comment]
#1971 here's the issue, will add an example of bug

**Comment by coder2020official** [comment]
@Badiboy overall hopefully I'm done, except for the last part where I had to change __html_text function. While implementing I encountered a bug, I'll try to fix it if can't I'll re-implement the function in another PR

**Comment by coder2020official** [comment]
No need for another PR, was able to fix the issue without rewriting it :)

**Comment by coder2020official** [comment]
@Badiboy btw if u r here can u please tell that u've read my message?

**Comment by Badiboy** [comment]
@coder2020official I'm here, but cannot follow so much notifiations, so I'm waiting for pin )
Ready for review?

**Comment by coder2020official** [comment]
Yess

**Review by Badiboy — APPROVED** [review]

**Comment by Badiboy** [comment]
@coder2020official I checked everything and do not see any moment even for comment :)
🤝

**Comment by coder2020official** [comment]
Yay! Merge then

**Comment by coder2020official** [comment]
Yay! Merge then

**Pull request merged**
