### PR TITLE
Testing out pyproject.toml instead of legacy setup.py

### PR DESCRIPTION
**Pull request by coder2020official**

### CODE REVIEW

**Comment by coder2020official** [comment]
@Badiboy take a look

**Comment by Badiboy** [comment]
@coder2020official I don't know anything about setups: never interested. If it really works - thus it's fine...

**Comment by coder2020official** [comment]
Then merge; Should work I guess

**Comment by coder2020official** [comment]
Oh btw... Version.py is now useless, I didn't delete it; I think some users get version from version.py, so let's leave it; So you will have to change version in both files

**Pull request merged**
