### PR TITLE
Bot API 7.4: Stars, effects, etc

### PR DESCRIPTION
**Pull request by coder2020official**
May 28, 2024
Bot API 7.4

- [x] Added support for payments in [Telegram Stars](https://t.me/BotNews/90) by introducing the new currency “XTR”.
- [ ] The parameter provider_token of the methods [sendInvoice](https://core.telegram.org/bots/api#sendinvoice) and [createInvoiceLink](https://core.telegram.org/bots/api#createinvoicelink) must be omitted for payments in [Telegram Stars](https://t.me/BotNews/90).
- [ ] The field provider_token in the class [InputInvoiceMessageContent](https://core.telegram.org/bots/api#inputinvoicemessagecontent) must be omitted for payments in [Telegram Stars](https://t.me/BotNews/90).
- [x] Added the method [refundStarPayment](https://core.telegram.org/bots/api#refundstarpayment).
- [x] Added the field effect_id to the class [Message](https://core.telegram.org/bots/api#message).
- [x] Added the parameter message_effect_id to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendInvoice](https://core.telegram.org/bots/api#sendinvoice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
- [x] Added the field show_caption_above_media to the classes [Message](https://core.telegram.org/bots/api#message), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif), [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto), [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo), [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif), [InlineQueryResultCachedMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultcachedmpeg4gif), [InlineQueryResultCachedPhoto](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto), and [InlineQueryResultCachedVideo](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo).
- [x] Added the parameter show_caption_above_media to the methods [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [copyMessage](https://core.telegram.org/bots/api#copymessage), and [editMessageCaption](https://core.telegram.org/bots/api#editmessagecaption).
- [x] Added support for “expandable_blockquote” entities in received messages.
- [x] Added support for “expandable_blockquote” entity parsing in “MarkdownV2” and “HTML” parse modes.
- [x] Allowed to explicitly specify “expandable_blockquote” entities in formatted texts.

### CODE REVIEW

**Comment by Badiboy** [comment]
> Dev said passing empty string for provider_token is fine

image

It is obviously mentioned in announcement )

**Comment by coder2020official** [comment]
Screenshot 2024-05-28 at 6 51 52 PM

**Comment by Badiboy** [comment]
image

@coder2020official , could you please clarify, why you used post here?

**Comment by Badiboy** [comment]
> it is made optional only for Telegram Stars; We have to maintain backward compatibility without changing position of parameter. What do you suggest?

I propose to allow users to pass NONE to this parameter (obviously) and add check
`if "provider_token" is not None:`
in helper.
This will allow to ommit this parameter in request and keep possibility to send empty string if needed.

**Comment by Badiboy** [comment]
Except "post" question and left comment LGTM.

**Comment by coder2020official** [comment]
If we make provider_token optional, backward compatibility will be gone

**Comment by Badiboy** [comment]
> If we make provider_token optional, backward compatibility will be gone

I said nothing about "make optional". I said "allow to pass NONE" :)

**Comment by coder2020official** [comment]
So I just change API helper as you said? And adjust the provider_token to Union[str, None]?

**Comment by Badiboy** [comment]
> So I just change API helper as you said? And adjust the provider_token to Union[str, None]?

Yep, I don't see other ways.

**Comment by coder2020official** [comment]
@Badiboy I think I'm done

**Comment by Badiboy** [comment]
@coder2020official Release?

**Comment by coder2020official** [comment]
No, there is one issue that needs to be closed before that;

**Pull request merged**
