### PR TITLE
Example bot using message reactions (emoji)

### PR DESCRIPTION
**Pull request by artyl**
## Description
Hello, I have created simple examples of bots (sync and async) that send emojis in response to received messages.

## Describe your tests
How did you test your change?
These are examples for them, tests are not needed.

Python version: All

OS: All

## Checklist:
- [x] I added/edited example on new feature/change (if exists)
- [x] My changes won't break backward compatibility
- [x] I made changes both for sync and async

### CODE REVIEW

**Comment by Badiboy** [comment]
What **new instruments** of the **library** this example demonstrate?

**Comment by coder2020official** [comment]
I'd add a reaction handler too

**Comment by artyl** [comment]
> What **new instruments** of the **library** this example demonstrate?

I struggled for quite a while until I figured out how to do it via Telebot, even though it was clear how to do it through the Telegram API. Since it wasn't obvious to me, I decided to make this example.

> I'd add a reaction handler too

What do you mean by reaction handler? As far as I understand, the bot does not receive a notification when someone adds a reaction; such functionality does not exist. Or did I misunderstand something?

**Comment by Badiboy** [comment]
> I struggled for quite a while until I figured out how to do it via Telebot

https://core.telegram.org/bots/api#setmessagereaction

All, absolutely all API methods have direct reflection in Telebot. Cannot imagine what may struggle in setting message reaction if you know how to, for example, send messages...

However more examples is better then less examples. Just rename it from emoji_bot.py to message_reaction.py or message_reaction_example.py.

**Comment by coder2020official** [comment]
And please use handlers to demonstrate a further usage

**Comment by coder2020official** [comment]
There're 2 reaction handlers if I'm not wrong

**Pull request closed without merging**
