### PR TITLE
Added support for local files in the sendMediaGroup method

### PR DESCRIPTION
**Pull request by heyyyoyy**
Added support for local files in the `send_media_group` method
For example:
```python
import telebot
from telebot.types import InputMediaPhoto, InputMediaVideo


bot = telebot.TeleBot(token)

@bot.message_handler(commands=['get'])
def get_media(message):
	with open('path/to/file1.jpg', 'rb') as f1, open('/path/to/file2.jpg', 'rb') as f2, \
		    open('/path/to/video.mp4', 'rb') as video:
		    files = bot.send_media_group(message.from_user.id,
		                                 [InputMediaPhoto(f1),
		                                  InputMediaPhoto(f2),
		                                  InputMediaPhoto(<url>),
		                                  InputMediaPhoto(<file_id>),
		                                  InputMediaVideo(video)])
```

### CODE REVIEW

**Comment by chebotarevmichael** [comment]
Thank you very much! It`s beatifull!)

**Comment by vSakun** [comment]
hello guys. how add any text for all album with photo?

**Comment by Badiboy** [comment]
> hello guys. how add any text for all photo album?

https://github.com/eternnoir/pyTelegramBotAPI/issues/1445#issuecomment-1033543719
No such instance as "Album". Thus no way to add text to it.

**Comment by vSakun** [comment]
> hello guys. how add any text for all photo album?

I understood. I mast to add context to only one picture.
`[telebot.types.InputMediaPhoto(image_first, some_text), telebot.types.InputMediaPhoto(image_second), telebot.types.InputMediaPhoto(image_third)]`

**Pull request merged**
