### PR TITLE
Update `apihelper.py`

### PR DESCRIPTION
**Pull request by TECH-SAVVY-GUY**
Add support for test mode in the Bot API

image

https://core.telegram.org/bots/webapps#testing-web-apps

### CODE REVIEW

**Comment by coder2020official** [comment]
@Badiboy it is still possible to set test env by manually setting the URL, but I think PR is still fine. But it would be maybe better to rename it to TEST_API_URL(?)

**Comment by Badiboy** [comment]
Do not see any value in this PR.

Setting
`API_URL = "https://api.telegram.org/bot{0}/test/{1}"`

Solve the task.

**Comment by TECH-SAVVY-GUY** [comment]
Added this because an entire section was dedicated on testing web apps in the Telegram API.

**Comment by Badiboy** [comment]
Do not see any value in this PR. Use API_URL.

**Pull request closed without merging**
