### PR TITLE
Import aioredis from redis module too

### PR DESCRIPTION
**Pull request by ananthb**
## Description
aioredis is available in redis-py as of version 4.2.0rc1: https://github.com/aio-libs/aioredis-py#-aioredis-is-now-in-redis-py-420rc1-
Try importing from the new package as well.

## Describe your tests
How did you test your change?
I tried async storage with aioredis from redis-py.

Python version: 3.10

OS: Linux

## Checklist:
- [ ] I added/edited example on new feature/change (if exists)
- [X] My changes won't break backward compatibility
- [ ] I made changes both for sync and async

### CODE REVIEW

**Comment by coder2020official** [comment]
Never tried. I'll take a look ASAP, thank you

**Comment by coder2020official** [comment]
This version is a pre-release, I think we don't need to replace it now

**Comment by ananthb** [comment]
That's just when it was introduced. Current stable 4.3 and above have the changes already.

**Comment by coder2020official** [comment]
LGTM, thanks.

**Comment by coder2020official** [comment]
But instead of just putting except, it'd be good to make it except ImportError

**Comment by coder2020official** [comment]
Or making 2 try-except blocks 'd look better.. let's wait for badiboy

**Comment by Badiboy** [comment]
I do not see something bad in the proposed method.

**Comment by coder2020official** [comment]
Great! Thanks

**Pull request merged**
