### PR TITLE
Added the ability to make blockquote expandable.

### PR DESCRIPTION
**Pull request by EgorKhabarov**
## Description
Include changes, new features and etc:
Added the ability to make blockquote expandable.

## Describe your tests
How did you test your change?
```python
bot.parse_mode = "HTML"
bot.send_message(chat_id, hcite("123"*123))
bot.send_message(chat_id, hcite("123"*123, expandable=True))
bot.parse_mode = "MarkdownV2"
bot.send_message(chat_id, mcite("123"*123))
bot.send_message(chat_id, mcite("123"*123, expandable=True))
```
image

Python version:

OS:

## Checklist:
- [ ] I added/edited example on new feature/change (if exists)
- [ ] My changes won't break backward compatibility
- [ ] I made changes both for sync and async

### CODE REVIEW

**Comment by Badiboy** [comment]
LGTM.

@coder2020official ?

**Comment by coder2020official** [comment]
Markdown supports it:
**>The expandable block quotation started right after the previous block quotation
>It is separated from the previous block quotation by an empty bold entity
>Expandable block quotation continued
>Hidden by default part of the expandable block quotation started
>Expandable block quotation continued
>The last line of the expandable block quotation with the expandability mark||

read more here:
https://core.telegram.org/bots/api#markdownv2-style

**Comment by EgorKhabarov** [comment]
Indeed! I didn't know that. Corrected.

**Comment by coder2020official** [comment]
and you tested different cases?

**Comment by EgorKhabarov** [comment]
Yes
```python
from telebot import TeleBot
from telebot.formatting import hcite, mcite


bot = TeleBot(token)

bot.parse_mode = "HTML"
bot.send_message(chat_id, hcite("123"*123))
bot.send_message(chat_id, hcite("123"*123, expandable=True))

bot.parse_mode = "MarkdownV2"
bot.send_message(chat_id, mcite("123"*123))
bot.send_message(chat_id, mcite("123"*123, expandable=True))
```

**Review by coder2020official — APPROVED** [review]

**Comment by Badiboy** [comment]
Thank you all )

**Pull request merged**
