### PR TITLE
Added option to delete messages.

### PR DESCRIPTION
**Pull request by Kylmakalle**
Added option to delete messages.

Some bots do not support `deleteMessage` method now, waiting for an official api update
release.

So, here is a small [script](https://gist.github.com/Kylmakalle/1132315523fee96c386b3330cdcdde13) to check possibility of your bot to delete messages **NOW**, while this method in non-release stage

**UPD: 08.05** Now 6/10 my bots can delete messages, telegram updates our bots gradually
**UPD: 12.05** 8/10 can delete messages, old bots updated.
**UPD: 14.05** 9/10 can delete messages, new bot updated

### CODE REVIEW

**Comment by Kylmakalle** [comment]
So, here is a small [script](https://gist.github.com/Kylmakalle/1132315523fee96c386b3330cdcdde13) to check possibility of your bot to delete messages **NOW**, when this method in non-release stage

**Comment by gmm96** [comment]
What kind of bots support this feature?
I tried with my 3 bots and the script returns "Can't delete" for all.

**Comment by Kylmakalle** [comment]
@gmm96 I have tried all my bots
2/7  Old bots can delete messages
2/3 New bots can delete messages

So, the suggestion is that it is about bot's DCs

**Comment by mafia-007** [comment]
function deletemessage(chat_id, message_id)
  local url = BASE_URL .. '/deletemessage?chat_id=' .. chat_id

  url = url .. '&message_id=' .. message_id

  return sendRequest(url)
end

**Comment by Kylmakalle** [comment]
**UPD:** Now 6/10 bots can delete messages, telegram updates our bots gradually

**Pull request merged**
