### PR TITLE
Add a function to extract contents of entities from messages

### PR DESCRIPTION
**Pull request by S1RANN**
## Description
Add `extract_entity` in  `util.py` to extract contents of entities from messages.

## Describe your tests
Send a message and compare the extracted contents of returned entities to the correct ones

Python version:3.10

OS: Windows

## Checklist:
- [x] I added/edited example on new feature/change (if exists)
- [x] My changes won't break backward compatibility
- [x] I made changes both for sync and async

### CODE REVIEW

**Comment by Badiboy** [comment]
As for me, I do not understand the purpose of the function.
Can you provide some use cases for it?

**Comment by S1RANN** [comment]
> As for me, I do not understand the purpose of the function. Can you provide some use cases for it?

Some apps create a share link which consists of a url and a description you can send to telegram, you can then let the bot grab some stuff like images from that. With this function you can acquire that url.

**Comment by S1RANN** [comment]
> But... Message have entities...
> 
> image
> 
> And entity has everything parsed...
> 
> image
> 
> https://core.telegram.org/bots/api#messageentity

There are two types of url, one is `url` : https://github.com and the other one is `text_link`: [Github](https://github.com).
That url field is just for the second type.
For the first one you have to parse it yourself.

**Comment by Badiboy** [comment]
Hmm.. That's true.

So, your function extratcs entity text by Message text and MessageEntity, right?

**Comment by S1RANN** [comment]
> Hmm.. That's true.
> 
> So, your function extratcs entity text by Message text and MessageEntity, right?

Yes

**Comment by Badiboy** [comment]
@coder2020official ?

**Comment by coder2020official** [comment]
Looks fine

**Pull request merged**
