### PR TITLE
Bot api 7.8

### PR DESCRIPTION
**Pull request by coder2020official**
- [x] Added the option for bots to set a [Main Mini App](https://core.telegram.org/bots/webapps#launching-the-main-mini-app), which can be previewed and launched directly from a button in the bot's profile or a link.
- [x] Added the method shareToStory to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).
- [x] Added the field has_main_web_app to the class [User](https://core.telegram.org/bots/api#user), which is returned in the response to [getMe](https://core.telegram.org/bots/api#getme).
- [x] Added the parameter business_connection_id to the methods [pinChatMessage](https://core.telegram.org/bots/api#pinchatmessage) and [unpinChatMessage](https://core.telegram.org/bots/api#unpinchatmessage), allowing bots to manage pinned messages on behalf of a business account.

### CODE REVIEW

**Comment by coder2020official** [comment]
I think I'm done: first two are mini app related

**Comment by coder2020official** [comment]
Let's release a new version immediately after merging this PR.
Then after releasing a new version, you will merge states PR

**Comment by coder2020official** [comment]
@Badiboy

**Comment by Badiboy** [comment]
LGTM. Thank you.

**Pull request merged**
