### PR TITLE
base_url added

### PR DESCRIPTION
**Pull request by coder2020official**
I've added a little change in base_url. It can be set in TeleBot class. Base_url helps to make a request to another API, local API.
Check tests in the tests folder.
Also, added an example in the example folder.

### CODE REVIEW

**Comment by Badiboy** [comment]
1. What's the reason to do it so complex?
Constructor => Parameter => set API
Why not simply set apihelper.API_URL before create Telebot?

2. This code:
```
         if base_url:
            apihelper.API_URL = base_url
```
is dangerous because may produce side effects. User assign **local paramterer** that will be inobviously assigned to **global variable**.

So, I do not see the any advantages of using
```
bot = telebot.TeleBot("token",base_url="http://localhost:8081")
```
instead of
```
apihelper.APU_URL="http://localhost:8081"
bot = telebot.TeleBot("token")
```

**Comment by coder2020official** [comment]
I've tested to set API_URL of apihelper, it didn't work. So, i added it to telebot class

**Comment by Badiboy** [comment]
Man, how it can "didn't work", if you do absolutely the same thing now?
image

**Comment by Badiboy** [comment]
Ah, I know why it didn't work for you.
`request_url = API_URL.format(token, method_name)

You should provide URL it appropriate format:
apihelper.API_URL = "http://localhost:8081/bot{0}/{1}"

And everything will be fine. If you have an **issue** - you should raise an **issue**, not a pull request. :)

**Comment by coder2020official** [comment]
But it would be better to add base url that can be set in TeleBot class.
But, adding with format options didn't work as i tried before. It returned:
http://localhost:8071/bot0/1
Instead of formatting options. I added the 'f' before string, no change.
I will retry after some time. Thank you

**Comment by coder2020official** [comment]
image
image
Look here)

**Comment by coder2020official** [comment]
I meant this also. So my pull request is useful 😄

**Comment by Badiboy** [comment]
Feel the difference between what I wrote:
`apihelper.APU_URL="http://localhost:8081"`
and what you wrote:
`apihelper.APU_URL=f"http://localhost:8081"`

**Comment by coder2020official** [comment]
image
image
No, still

**Comment by Badiboy** [comment]
You assign the string. Then print it. What you extected to see there?!

Are we playing in kindergarden?

**Comment by coder2020official** [comment]
Oops

**Comment by coder2020official** [comment]
But ptb has base url if i am not mistaken.. it wouldn't be bad if we d add

**Comment by Badiboy** [comment]
Here:
https://github.com/eternnoir/pyTelegramBotAPI/pull/1192#issuecomment-864384814
i mentined 2 points why this update have no value and is dangerous.

**Comment by SwissCorePy** [comment]
> I've tested to set API_URL of apihelper, it didn't work. So, i added it to telebot class

You have to set it to `http://localhost:PORT/bot{0}/{1}`
This works :)

**Comment by SwissCorePy** [comment]
> image
> image
> Look here)

it does not work because you set apihelper.API_URL to "httP://localhost:PORT/bot0/1" beacause you make an expression (f-string). But this string is formated later by making a request usin API_URL.format(token, method_name). 
just delete the f before your string and it should work

**Comment by coder2020official** [comment]
Yes, this is fixed now, but it'd be easier to add it as base_url :/

**Comment by SwissCorePy** [comment]
> Yes, this is fixed now, but it'd be easier to add it as base_url :/

It makes no big difference but would be a good option too :)

**Pull request closed without merging**
