### PR TITLE
Bot API 3.3

### PR DESCRIPTION
**Pull request by MasterGroosha**
- Added the new field pinned_message to the Chat object.
- Added the new fields author_signature and forward_signature to the Message object.
- Added the new field is_bot to the User object.

### CODE REVIEW

**Comment by maxkrivich** [comment]
@MasterGroosha I have some problems with pinned message. How to set the message as a pin. I'm breaking my head to solve it. I see filed but, how to do it I don't know.

**Comment by MasterGroosha** [comment]
@maxkrivich bot.pin_chat_message(chat_id, message_id)

**Comment by maxkrivich** [comment]
@MasterGroosha thank you very much. I search in repo "pin", but nothing found.

**Comment by alfilesnet** [comment]
def pin_chat_message(token, chat_id, message_id, disable_notification=False):
    method_url = 'pinChatMessage'
    payload = {'chat_id': chat_id, 'message_id': message_id, 'disable_notification': disable_notification}
return _make_request(token, method_url, params=payload, method='post')


You have to write the message id, not a message.

For example:
bot.pin_chat_message(-1234567, 214 (or m.message_id))

**Pull request merged**
