### PR TITLE
Just a small README update

### PR DESCRIPTION
**Pull request by SwissCorePy**
* Added the new message_handlers
* Added some information about local Bot API Server
* Replaced the split_string with the smart_split function

### CODE REVIEW

**Comment by Badiboy** [comment]
image

Let's keep both versions in readme?

**Comment by SwissCorePy** [comment]
> image
> 
> Lets keep both versions in readme?

ok :)

**Comment by Badiboy** [comment]
*hugs*

**Comment by SwissCorePy** [comment]
too  \( ﾟヮﾟ)/

**Pull request merged**
