### PR TITLE
new advanced TextFilter was added && An example demostrating TextFilt…

### PR DESCRIPTION
**Pull request by abdullaev388**
…er usage

### CODE REVIEW

**Review by coder2020official — CHANGES_REQUESTED** [review]
Remove your token.
Instead of prints send a message
In filter, instead of checking ignore_case all time, check once.

**Comment by abdullaev388** [comment]
> Remove your token. Instead of prints send a message In filter, instead of checking ignore_case all time, check once.

removed token, modified ignore_case checks but can't send message in poll_handler that handler do not provide chat_id

**Comment by coder2020official** [comment]
I hope you tested?

**Comment by coder2020official** [comment]
Example on asyncio filter is totally wrong

**Comment by coder2020official** [comment]
You can delete asyncio filter example. I will remake it myself.
And for other examples I hope you have tested it.

**Review by coder2020official — APPROVED** [review]

**Pull request merged**
