### PR TITLE
Added ability to set parse_mode by default

### PR DESCRIPTION
**Pull request by daveusa31**
In functions

send_message
send_photo
send_voice
send_document
send_video
send_animation
edit_message_text
edit_message_caption

### CODE REVIEW

**Comment by barbax7** [comment]
Why not update also on pypi?

**Comment by Badiboy** [comment]
Not every update comes to release. We'll try.

**Comment by barbax7** [comment]
Because of some pypi policies? It's the first time I've come to this world

Andrea Barbagallo
andreabarbagallo.ab7@gmail.com

________________________________

**Comment by daveusa31** [comment]
Therefore, it is not because of each new feature that you should release a new version

**Comment by barbax7** [comment]
So, if someone install from pypi, he won't have the new features, right?

Andrea Barbagallo
andreabarbagallo.ab7@gmail.com

________________________________

**Comment by daveusa31** [comment]
Until the new version is released, it won't be

**Comment by daveusa31** [comment]
You can install this commit
`pip install https://github.com/eternnoir/pyTelegramBotAPI/archive/e9f925e14cd3b32a1e778bf8465e3d7b3af14dc8.zip`

Or all the latter
`pip install https://github.com/eternnoir/pyTelegramBotAPI/archive/master.zip`

**Comment by Badiboy** [comment]
Version 3.7.2 released.

**Pull request merged**
