### PR TITLE
Added handlers for `my_chat_member` and `chat_member`

### PR DESCRIPTION
**Pull request by SwissCorePy**
I know, no more updates for now, but i think this small addition was needed.
I hope this is ok for you :)

### CODE REVIEW

**Comment by Badiboy** [comment]
image

What's the reason? Why this is better then default behaviour (without allowed_updates)?

**Comment by SwissCorePy** [comment]
> image
> 
> What's the reason? Why this is better then default behaviour (without allowed_updates)?

It's necessary because `chat_member` is not requested by default

Bildschirmfoto 2021-06-23 um 18 27 08

**Comment by Badiboy** [comment]
Ops, that's interesting. I suppose Telegram has the reason to set the default behaviour in that way. So may be we should left the default behaviour also but let user to extend it with chat member?

If you agree, I'll take a look what can be a suitable solution.

**Comment by Badiboy** [comment]
PS: I think I see the reason. If you have a group with 20K users your bot will receive tonns of chat_member updates even if nothing else happen in group and even if you do not need them at all. Your system may have a significant workload for nothing.

**Comment by SwissCorePy** [comment]
Ok :) We could let the user set this as argument in bot.polling()

**Comment by SwissCorePy** [comment]
> PS: I think I see the reason. If you have a group with 20K users your bot will receive tonns of chat_member updates even if nothing else happen in group and even if you do not need them at all. Your system may have a significant workload for nothing.

Yes you are right

**Comment by SwissCorePy** [comment]
I have two solutions for that problem.
1. new bool parameter `allow_member_updates` in bot.polling/bot.infinity_polling (default False)
2. new list parameter `allowed_updates` in bot.polling/bot.infinity_polling (default None)

I would prefer the second solution, because it lets the user exactly define which updates he want to recieve. and i think it is more "future-proof".

What do you think? Or do you have a better solution in mind?

**Comment by SwissCorePy** [comment]
sorry for the more commits, just say it if i have to stop

**Comment by Badiboy** [comment]
> sorry for the more commits, just say it if i have to stop

You should ))))))))))

**Comment by Badiboy** [comment]
> What do you think? Or do you have a better solution in mind?

Looks fine, thank you.

**Comment by Badiboy** [comment]
@SwissCorePy Just FYI. I installed all updates on my production system. If everything will work fine - tomorrow I'll publish the release.

**Comment by SwissCorePy** [comment]
Cool thanks

**Comment by Badiboy** [comment]
image

Ups. I'll fix :)

**Comment by SwissCorePy** [comment]
> image
> 
> Ups. I'll fix :)

whoops sorry ^^

**Pull request merged**
