### PR TITLE
Bump version to 4.10.0

### PR DESCRIPTION
**Pull request by Badiboy**

### CODE REVIEW

**Comment by coder2020official** [comment]
4.10? Why,?

**Comment by Badiboy** [comment]
[4.8.0 - Bot API 6.3](https://github.com/eternnoir/pyTelegramBotAPI/releases/tag/4.8.0)
[4.9.0 - Bot API 6.4](https://github.com/eternnoir/pyTelegramBotAPI/releases/tag/4.9.0)
[4.10.0 - Bot API 6.5](https://github.com/eternnoir/pyTelegramBotAPI/releases/tag/4.10.0)

What's wrong?

**Comment by coder2020official** [comment]
And no need to include me in release notes anymore xD

**Comment by Badiboy** [comment]
> And no need to include me in release notes anymore xD

OK

**Comment by coder2020official** [comment]
I thought u'd release 5.0.0, cuz we never had number 10 afaik in the middle
We had 3.8.3 turning to 4.0.0
But I don't memorise any X.10.X version

**Comment by Badiboy** [comment]
> I thought u'd release 5.0.0, cuz we never had number 10 afaik in the middle

Major version change is the subject of something fundamentaly new in the library, but not just because we reach 10 in the middle :)

**Comment by coder2020official** [comment]
Idk, then u could release 4.9.5 or 4.9.1

**Comment by rdlrt** [comment]
>  then u could release 4.9.5 or 4.9.1

The versioning (4.9.0 - Bot API 6.4 => 4.10.0 - Bot API 6.5) is in line with [standard semantic versioning](https://semver.org/).

It is a minor release, as new functionality (bot API support for 6.5) was added and is backwards compatible. It isnt a bug-fix for it to be updating patch version.

**Pull request merged**
