### PR TITLE
Deprecation: stubs for Message fields in InaccessibleMessage

### PR DESCRIPTION
**Pull request by Badiboy**
Deprecation stubs for Message fields in InaccessibleMessage to prevent user code exceptions.

Added named parameters in html_text.

### CODE REVIEW

**Comment by coder2020official** [comment]
Did you test the change regarding inaccessible message? Works?

**Comment by coder2020official** [comment]
And please test html text just in case))

**Comment by Badiboy** [comment]
I tested the implementation made for InaccessMessage on syntetic test class. 

html_text workd fine on [this](https://core.telegram.org/bots/api#html-style).

**Comment by Badiboy** [comment]
@coder2020official Release is awaiting )

**Comment by coder2020official** [comment]
LGTM, but I wouldn't hurry with another release?

**Pull request merged**
