### PR TITLE
is_private filter

### PR DESCRIPTION
**Pull request by coder2020official**
Recently, when I tried to add some filters, you rejected and said, the only is_private can be useful. So I created is_private filter

### CODE REVIEW

**Comment by Badiboy** [comment]
In my oppinion, 
_is_private_
naming is confusing. 

is_private == True - it's clear.

is_private == False - it's confusing.
Does it means NOT PRIVATE (i..e. only groups) or not ONLY private...

May be some other naming? 
"only_private"? for example?

**Comment by coder2020official** [comment]
Ok

**Comment by Badiboy** [comment]
@SwissCorePy - could you please give your oppinion about the naming?

**Comment by SwissCorePy** [comment]
> @SwissCorePy - could you please give your oppinion about the naming?

i recommend making a chat_types filter insted. which defaults to ["private", "group", "supergroup","channel"] when not set.
Eg. 
`@bot.message_handler(chat_types=["private"])`
`@bot.message_handler(chat_types=["group", "supergroup"])`
`@bot.message_handler(chat_types=["channel"])`

**Comment by coder2020official** [comment]
Ok, i will recommit

**Comment by coder2020official** [comment]
Recommited, what do you think?

**Comment by coder2020official** [comment]
I think we don't need default parameter. If it will be None by default, it will work :)
*And, we have another handler for channels, so chat type can't be channel 🤔  @SwissCorePy

**Comment by SwissCorePy** [comment]
Looks good for me :)

> I think we don't need default parameter. If it will be None by default, it will work :)
I mean how it behaves by default if not set.

> *And, we have another handler for channels, so chat type can't be channel 🤔 @SwissCorePy
True. my fault ^^

**Comment by Badiboy** [comment]
> i recommend making a chat_types filter insted

Thanks, bro! Good idea, clear and corresponds well with other handlers.

**Comment by Badiboy** [comment]
@coder2020official thank you! Let's try )

**Pull request merged**
