### PR TITLE
Fix broken text_mention html formatting

### PR DESCRIPTION
**Pull request by andvch**

### CODE REVIEW

**Comment by BLUE-DEVIL1134** [comment]
it is correct
whats the error

**Comment by Badiboy** [comment]
This code was done looong ago and I definitely cannot check if the fix is correct or not.
Can you please provide test case results before fix and after it?

**Comment by andvch** [comment]
Sure
```
import telebot

json = '{ \
	"message_id": 123, \
	"from": {"id": 111111111, "is_bot": false, "first_name": "User", "username": "user"}, \
	"chat": {"id": -10000000, "title": "Chat", "type": "supergroup"}, \
	"date": 1602751500, \
	"text": "Hello, user!", \
	"entities": [{ \
		"offset": 7, \
		"length": 4, \
		"type": "text_mention", \
		"user": {"id": 123456789, "is_bot": false, "first_name": "UserWithoutUsername"} \
	}] \
}'

message = telebot.types.Message.de_json(json)
print(message.html_text)

# before fix:
# Hello, user!

# after it:
# Hello, <a href="tg://user?id=123456789">user</a>!

```

**Comment by Badiboy** [comment]
Thank you!

**Pull request merged**
