### PR TITLE
skip_updates

### PR DESCRIPTION
**Pull request by coder2020official**
Added skip_updates
It skip old updates except last one.
Added only to polling and infinity polling. Added example too.
As telegram api says in getUpdates method:
The negative offset can be specified to retrieve updates starting from -offset update from the end of the updates queue. All previous updates will forgotten.
I passed negative 1 as offset
Results are shown in images
Before skip updates
Screen Shot 2021-08-15 at 11 45 19
After 
Screen Shot 2021-08-15 at 11 45 53
As I understood, by passing negative offset will clear all updates except the latest one.

### CODE REVIEW

**Comment by Badiboy** [comment]
1.
image
That's not exactly what you did (can be used only on bot creation, but is very simillar.

2.
image
There is a method to skip updates. It's better to use it or update it if you'll find that it's not suitable.

**Comment by coder2020official** [comment]
Ok, i will recommit today

**Comment by coder2020official** [comment]
Do you think i need to delete skip_pending and instead put it in polling as skip_update?
I think putting in polling method would be better. Then i will rewrite method you have shown to skip updates

**Comment by coder2020official** [comment]
Removed skip_pending and put instead skip_updates in polling method.

**Comment by Badiboy** [comment]
> Do you think i need to delete skip_pending and instead put it in polling as skip_update?

We cannot delete :)

**Comment by Badiboy** [comment]
> Do you think i need to delete skip_pending and instead put it in polling as skip_update?

We cannot delete existing parameters. :) Compatibility. :(

Additionally I propose to name parameter "skip_pending" to be common to one in Init.

**Comment by coder2020official** [comment]
Aiogram has skip_updates=True in executor, i was getting some things a from there
It is better to put this parameter in polling, isn't it?

**Comment by coder2020official** [comment]
So, what do you think of skip_updates in polling method?

**Comment by coder2020official** [comment]
Made like you said

**Comment by coder2020official** [comment]
I have a second pull request, can u merge or comment this

**Comment by Badiboy** [comment]
> So, what do you think of skip_updates in polling method?

Have nothing against it: why not to have it in both places and let user use what he prefer.

But in my oppinion skip_pending naming in polling/infinity_polling is preferrable to be consistent with skip_pending in Init... What do you think?

**Comment by coder2020official** [comment]
Updated, now it can be used in 2 places

**Comment by Badiboy** [comment]
Amazing. :)

**Pull request merged**
