### PR TITLE
Use native requests/urllib3 retry mechanism

### PR DESCRIPTION
**Pull request by ofen**
https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Retry

### CODE REVIEW

**Comment by Badiboy** [comment]
Any reasoning of this update? What's wrong with existing implementation?

**Comment by Badiboy** [comment]
1. Debug information is dropped.
2. Session handling is dropped.

It needs valuable argument for such update.

**Comment by ofen** [comment]
Hi, @Badiboy. This one reduce delays after network error/re-connection and works better on slow networks (e.g. cellular).

**Comment by coder2020official** [comment]
Is this still valid?

**Comment by ofen** [comment]
@coder2020official hi! The issue still persists. Current retry implementation may hang on unstable network connection and recovers with 10-40s delays.

**Comment by coder2020official** [comment]
I highly recommend using retry_on_error. This helped me a lot. Even when I put PC into sleep mode, it didn't stop.
`
telebot.apihelper.RETRY_ON_ERROR = True
bot.polling()
`

**Comment by coder2020official** [comment]
Also:
How can I handle reocurring ConnectionResetErrors?
Bot instances that were idle for a long time might be rejected by the server when sending a message due to a timeout of the last used session. Add `apihelper.SESSION_TIME_TO_LIVE = 5 * 60` to your initialisation to force recreation after 5 minutes without any activity.

**Comment by Badiboy** [comment]
@ofen 
https://github.com/eternnoir/pyTelegramBotAPI/pull/1356

Will this way be ok for your proposal and needs?

**Pull request closed without merging**
