### PR TITLE
Added Flask Google Cloud bot's example

### PR DESCRIPTION
**Pull request by xinitd**
## Description
Simple bot for Google cloud deployment.
"main.py" file contain bot and Flask webhooks for easy deployment in Google Cloud.
"requirements.txt" file contain all tested dependencies.
"app.yaml" need for Google Cloud Appengine environment.

Python version: 3.8

Dev environment: Debian 12.5

### CODE REVIEW

**Comment by Badiboy** [comment]
image

What for all that requirements?

**Comment by xinitd** [comment]
This packages coming when install requirements from Documentation:
https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-python-service#writing
Screenshot_2024-04-28_16-49-06
Screenshot_2024-04-28_16-50-19

**Comment by Badiboy** [comment]
image
This is fine.

https://github.com/eternnoir/pyTelegramBotAPI/pull/2246#issuecomment-2081441935
This is not.

**Comment by xinitd** [comment]
Now i fixed dependencies

Screenshot 2024-04-29 at 00-20-42 Added Flask Google Cloud bot's example by xinitd · Pull Request #2246 · eternnoir_pyTelegramBotAPI

**Comment by Badiboy** [comment]
👍

**Pull request merged**
