### PR TITLE
fix: 'new_chat_participant' => 'new_chat_member'

### PR DESCRIPTION
**Pull request by MrMebelMan**
Update the field name in `telebot_bot.py` example and fix the content_types field.

### CODE REVIEW

**Comment by Badiboy** [comment]
image

Seems still wrong?

**Comment by MrMebelMan** [comment]
@Badiboy, nah, this is correct, only the content-type is in plural :+1:

**Comment by Badiboy** [comment]
Lib has the following code:

        self.new_chat_member = None
        self.new_chat_members = None
        ...
        if 'new_chat_member' in obj:
            opts['new_chat_member'] = User.de_json(obj['new_chat_member'])
            content_type = 'new_chat_member'
        if 'new_chat_members' in obj:
            chat_members = obj['new_chat_members']
            nms = []
            for m in chat_members:
                nms.append(User.de_json(m))
            opts['new_chat_members'] = nms
            content_type = 'new_chat_members'
  
But Telegram Bot API has only

new_chat_members | Array of User | Optional. New members that were added to the group or supergroup and information about them (the bot itself may be one of these members)
-- | -- | --

https://core.telegram.org/bots/api#message

I suppose that **new_chat_member** property and content type are outdated and should be removed from the code of the library as unreachable.

**Comment by MrMebelMan** [comment]
Oh. Thanks!

**Pull request closed without merging**
