### PR TITLE
2 of 3 Bot API 5.3 changes

### PR DESCRIPTION
**Pull request by MAIKS1900**
- Personalized Commands for different chats
- Custom Placeholders of input field for ReplyKeyboardMarkup and ForceReply.

### CODE REVIEW

**Comment by MAIKS1900** [comment]
#1202

**Comment by SwissCorePy** [comment]
I've already implemented all new features, but Badiboy need some time to test the latest updates untill we make new major pull requests ;)

**Comment by MAIKS1900** [comment]
Oh, can't wait for new version. So I'm closing pull

**Comment by coder2020official** [comment]
Well, you can reopen because new version already got released

**Comment by MAIKS1900** [comment]
Sorry, it seems I already deleted fork, so can't reopen this pull request. Created new one: #1206

**Pull request closed without merging**
