### PR TITLE
Added nested entities from Bot API 4.5

### PR DESCRIPTION
**Pull request by EskiSlav**

### CODE REVIEW

**Comment by Badiboy** [comment]
image

What's the reason for changing this comment?

**Comment by EskiSlav** [comment]
> image
> 
> What's the reason for changing this comment?

changed it because in telegram version 4.5 had been added next entities: `strikethrough` and `underline`, so I added  them to the `_sub` dictionary so it works and there is no need to add entities from telegram 4.5 update ...

**Comment by Badiboy** [comment]
This commend tells that, that NESTED entities should be implemented.

image

**Comment by EskiSlav** [comment]
> This commend tells that, that NESTED entities should be implemented.
> 
> image

Thanks for your observation. I'll fix that

**Pull request closed without merging**
