### PR TITLE
Fixed the errors from my last PRs

### PR DESCRIPTION
**Pull request by SwissCorePy**
So, now i testet everything usin pytest and python versions 3.6-3.9 on macOS.
I hope this is now acceptable. Sorry again for my mistakes, I'm pretty new on GitHub.

Here the output from my tests:

```
fredi@fredis-Hackintosh pyTelegramBotAPI % /usr/local/bin/python3.6 -m pytest
============================================== test session starts ===============================================
platform darwin -- Python 3.6.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/fredi/Documents/GitHub/pyTelegramBotAPI
collected 98 items                                                                                               

tests/test_handler_backends.py .......ss                                                                   [  9%]
tests/test_telebot.py ..............................................................                      [ 72%]
tests/test_types.py ...........................                                                           [100%]

=================================== 96 passed, 2 skipped in 143.27s (0:02:23) ===================================
fredi@fredis-Hackintosh pyTelegramBotAPI % /usr/local/bin/python3.7 -m pytest
============================================== test session starts ==============================================
platform darwin -- Python 3.7.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/fredi/Documents/GitHub/pyTelegramBotAPI
collected 98 items                                                                                              

tests/test_handler_backends.py .......ss                                                                  [  9%]
tests/test_telebot.py ..............................................................                      [ 72%]
tests/test_types.py ...........................                                                           [100%]

=============================================== warnings summary ================================================
../../../Library/Python/3.7/lib/python/site-packages/requests/packages/urllib3/_collections.py:1
../../../Library/Python/3.7/lib/python/site-packages/requests/packages/urllib3/_collections.py:1
  /Users/fredi/Library/Python/3.7/lib/python/site-packages/requests/packages/urllib3/_collections.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Mapping, MutableMapping

tests/test_telebot.py::TestTeleBot::test_send_message_with_markdown
  /Users/fredi/Library/Python/3.7/lib/python/site-packages/requests/models.py:169: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if isinstance(hook, collections.Callable):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================== 96 passed, 2 skipped, 3 warnings in 21.21s ===================================
fredi@fredis-Hackintosh pyTelegramBotAPI % /usr/local/bin/python3.8 -m pytest
============================================== test session starts ==============================================
platform darwin -- Python 3.8.8, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/fredi/Documents/GitHub/pyTelegramBotAPI
collected 98 items                                                                                              

tests/test_handler_backends.py .......ss                                                                  [  9%]
tests/test_telebot.py ..............................................................                      [ 72%]
tests/test_types.py ...........................                                                           [100%]

=================================== 96 passed, 2 skipped in 140.51s (0:02:20) ===================================
fredi@fredis-Hackintosh pyTelegramBotAPI % /usr/local/bin/python3.9 -m pytest
============================================== test session starts ==============================================
platform darwin -- Python 3.9.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/fredi/Documents/GitHub/pyTelegramBotAPI
collected 98 items                                                                                              

tests/test_handler_backends.py .......ss                                                                  [  9%]
tests/test_telebot.py ..............................................................                      [ 72%]
tests/test_types.py ...........................                                                           [100%]

=================================== 96 passed, 2 skipped in 141.67s (0:02:21) ===================================
fredi@fredis-Hackintosh pyTelegramBotAPI % 
```

### CODE REVIEW

**Comment by Badiboy** [comment]
image

Damn. It's very interesting, but I cannot evaluate if it is fully conformant visually.

**Comment by Badiboy** [comment]
image

PyCharm (for example) does not like such typing. With your update my screen is now is full of warnings. What we can do with this? I suppose it should be update to propper typing for "value or None". Disabling type checking will waste all this update...

**Comment by SwissCorePy** [comment]
I could change it to Union[Chat, None] for example, this should allow none as well

**Comment by SwissCorePy** [comment]
> image
> 
> Damn. It's very interesting, but I cannot evaluate if it is fully conformant visually.

What do you mean?

**Review by Badiboy — COMMENTED** [review]
> > Damn. It's very interesting, but I cannot evaluate if it is fully conformant visually.
> What do you mean?

I mean it needs much attention. :)) Nothing from your side :)

**Comment by Badiboy** [comment]
> I could change it to Union[Chat, None] for example, this should allow none as well

I checked the PR. Seems it should work. More or less. :)

If you promise to update types to Unions (or something what will conform with "value or None" in reasonable time - I propose to Merge this PR and start new one for the update to avoid growing of code updates in one PR. 

What do you think?

**Comment by SwissCorePy** [comment]
Thank you :)
Yes that sounds good. I have time today, so i will start today. I will use pycharm to make sure to get rid off all of this warnings.

**Pull request merged**
