### PR TITLE
Added some missing features

### PR DESCRIPTION
**Pull request by SwissCorePy**
* Added some missing classes, functions and variables from TelegramBotAPI 4.5-5.2 to pyTelegramBotAPI
* Added type hints for (almost) all TeleBot functions

### CODE REVIEW

**Comment by Badiboy** [comment]
Bro, if you will not stop - we'll never publish the update :)))

**Comment by Badiboy** [comment]
`thumb: Union[Any, str]`

What's the reason of typing "Any"? Especially "Any" or "str"?

**Comment by SwissCorePy** [comment]
> `thumb: Union[Any, str]`
> 
> What's the reason of typing "Any"? Especially "Any" or "str"?

its a placeholder for now. i think we can use bytes or _pyio.BufferedReader.

> Bro, if you will not stop - we'll never publish the update :)))

Haha, sorry should i slow down a little bit? ^^

**Comment by Badiboy** [comment]
image
Ops

**Comment by Badiboy** [comment]
image

I suppose that boolean values should be checkd on None obviously:
`if not (allow_sending_without_reply is None):`
Otherwise we will loose "False" values. It MAY work if the default value on the Telegram side is False, but we cannot be sure what's going on there. So I propose to have obvious check for bools

**Comment by Badiboy** [comment]
Ufff, I spend an hour+ just to review it. Huge work, bro!

**Comment by SwissCorePy** [comment]
> image
> 
> I suppose that boolean values should be checkd on None obviously:
> `if allow_sending_without_reply is not None:`
> Otherwise we will loose "False" values. It MAY work if the default value on the Telegram side is False, but we cannot be sure what's going on there. So I propose to have obvious check for bools.
> 
> image
> Like here. :)

oh oops yes you're right, ill fix that

**Comment by SwissCorePy** [comment]
> image
> Ops

xD typed that name to often to today ^^ is fixed

**Comment by SwissCorePy** [comment]
okey, the bool values in all `to_dict` functions are now checked `if not None`.
But i wait untill you've reviewed the current PR. because also added the class`InputInvoiceMessageContent` and support for tgs stickers.

**Comment by Badiboy** [comment]
I'm done with this one.

**Comment by SwissCorePy** [comment]
ok perfect :) i do new PR after finsishing the tests

**Pull request merged**
