### PR TITLE
Formatting using f-strings.

### PR DESCRIPTION
**Pull request by Maxdha**
f-strings are faster than format() and %-formatting .

### CODE REVIEW

**Comment by Badiboy** [comment]
> f-strings are faster than format() and %-formatting .

Any proof?

**Comment by Maxdha** [comment]
It's drastically faster.
##########

```
>>> from timeit import timeit
>>> timeit("'{0}'.format(999999999999)")
0.3178925239990349
>>> timeit("f'{999999999999}'")
0.13962799000000814

```

**Comment by Maxdha** [comment]
Sorry, my example was completely wrong. I've edited it.

**Comment by Badiboy** [comment]
I'm not sure that all these updates are 100% vulnerability safe. For example, if you run someone else bot, ask him for token and he pass you some command string as token...

`request_url = f"https://api.telegram.org/bot{token}/{method_name}"`

I'm very sorry, but I have no time now to explore it deeply. These updates are "beautifiers" and in fact give no value to the library and its users.

**Pull request closed without merging**
