### PR TITLE
Improve Docs

### PR DESCRIPTION
**Pull request by BLUE-DEVIL1134**
Just A Small Help To Improve The Docs..

### CODE REVIEW

**Comment by BLUE-DEVIL1134** [comment]
**Sir Can You Please Merge It Fast..**

**Comment by Badiboy** [comment]
@BLUE-DEVIL1134  So... 

image

You simply renamed "tb" to "bot" and assume that this update is (a) valuable and (b) **so valuable** so you push it with **bold message**? Seriously?

**Comment by BLUE-DEVIL1134** [comment]
acctually i am doing this for hactoberfest

**Comment by Badiboy** [comment]
You choose the wrong place for your games.

**Pull request closed without merging**
