### PR TITLE
Added link for WebApp examples.

### PR DESCRIPTION
**Pull request by TECH-SAVVY-GUY**
Hi, based on the latest Web App update, I have included a link to some example Web Apps using this library.

I will be adding more examples in the future too.

### CODE REVIEW

**Comment by Badiboy** [comment]
There is no examples. There are just 3 links to external resources. What's their purpose in **library** readme?

**Comment by TECH-SAVVY-GUY** [comment]
Since, the webapps are hosted through GitHib integration, I can't add it in the examples folder. That's why I linked it to the repo.

**Comment by Badiboy** [comment]
Examples of the library are not covered with integrations. You can add examples to the folder.

**Comment by TECH-SAVVY-GUY** [comment]
Can you kindly take a look at the repository and tell me how exactly I should add these examples? 

Since Web Apps need to be hosted, there is a definite file structure. (I am using Flask) 

How do you propose, I create the examples while maintaining the file structure and simultaneously hosting it? 

I asked coder2020 about this on Telegram, he also said to add links.

**Comment by Badiboy** [comment]
@TECH-SAVVY-GUY Amazing practice to place private chats to public githгb. Applause.

**Comment by Badiboy** [comment]
image

What is the problem to create a folder in examples and put these (some of them) files to it? 
If you need it running elsewhere - it's fine, keep it there also.

**Comment by TECH-SAVVY-GUY** [comment]
> What is the problem to create a folder in examples and put these (some of them) files to it? 
> If you need it running elsewhere - it's fine, keep it there also.

Instead of uploading the same files again, what's the problem to simply add a link to it?

**Comment by TECH-SAVVY-GUY** [comment]
> @TECH-SAVVY-GUY Amazing practice to place private chats to public github. Applause.
> 
> 

Well, it was in reference to this pull request only, and it didn't reveal any private information. So I thought I should share it as he's one of the library developers. 

If you want, I can delete the screenshot.

**Comment by coder2020official** [comment]
I think link is better, because adding those files to examples will confuse   
users a bit...

**Comment by Badiboy** [comment]
Close?

**Comment by TECH-SAVVY-GUY** [comment]
> Close?
Why? I think adding the link to the examples will be very useful to the users 🤔

**Comment by Badiboy** [comment]
Full example code should be added to the project folder and commited to the project.

You can put link in exaples readme/code if you want to keep the author referral.

**Comment by TECH-SAVVY-GUY** [comment]
> Full example code should be added to the project folder and commited to the project.

As @coder2020official mentioned, uploading so many files and folders will confuse the users.

> You can put link in exaples readme/code if you want to keep the author referral.

I opened the PR for this reason itself. I have added the link to the README.

**Comment by TECH-SAVVY-GUY** [comment]
@Badiboy Can you kindly explain why you closed this PR? 

I don't think adding the link would have caused any problems? Instead it would have helped many users to get started with Web Apps 🤷🏻‍♂️

**Comment by Badiboy** [comment]
@TECH-SAVVY-GUY I obviously texted my position. Several times.

**Comment by TECH-SAVVY-GUY** [comment]
> @TECH-SAVVY-GUY I obviously texted my position. Several times.
>> You can put link in exaples readme/code if you want to keep the author referral.

What does this mean then?

**Pull request closed without merging**
