### PR TITLE
HTML formatting fix. Added method html_text in telebot.types.TextQuote.

### PR DESCRIPTION
**Pull request by EgorKhabarov**
## Description
Include changes, new features and etc:
`telebot.types.Message.html_text` now cannot contain unescaped characters.

> The user sends `<b>b</b> <i>i</i>` (without markdown characters) and as an html string I expect to receive the escaped characters `&lt;b&gt;b&lt;/b&gt; &lt;i&gt;i&lt;/i&gt;`
> If the user sends `**b** <b>b</b> <i>i</i>` (with markdown characters) then I get `<b>b</b> &lt;b&gt;b&lt;/ b&gt; &lt;i&gt;i&lt;/i&gt;`.

`telebot.types.TextQuote` now supports the `html_text` method

## Describe your tests
How did you test your change?
added test to `tests/test_types.py`

Python version: 3.11.6

OS: Windows 10

## Checklist:
- [X] I added/edited example on new feature/change (if exists)
- [X] My changes won't break backward compatibility
- [X] I made changes both for sync and async

### CODE REVIEW

**Comment by Badiboy** [comment]
image

WTF?

**Comment by EgorKhabarov** [comment]
move `__html_text` to `telebot/formatting.py`?

**Comment by Badiboy** [comment]
I don't understand why TWO __html_text appeared.

**Comment by EgorKhabarov** [comment]
image
I decided to add a second `__html_text` function since quote doesn't support some entities.
But `Message.__html_text` is suitable for `TextQuote`.
I suggest moving `__html_text` to `formatting.py` and using it for both classes.

**Comment by EgorKhabarov** [comment]
I moved `__html_text` to `formatting.py` as `apply_html_entities`.

**Comment by coder2020official** [comment]
I will take a look later on. Thanks for the PR

**Comment by coder2020official** [comment]
LGTM. Just move the function in formatting file to the end to keep the order

**Comment by Badiboy** [comment]
If @coder2020official said "LGTM" :)

**Comment by Badiboy** [comment]
@EgorKhabarov 
Please, address the issue for python 3.8
https://github.com/eternnoir/pyTelegramBotAPI/actions/runs/8772384699/job/24071257729

**Pull request merged**
