### PR TITLE
added InputInvoiceMessageContent and tgs_sticker support

### PR DESCRIPTION
**Pull request by SwissCorePy**
* Added InputInvoiceMessageContent
* Added tgs_sticker support 
* changed Union[Type, None] type hints to Optional[Type]

(that's it for today :D )

### CODE REVIEW

**Comment by Badiboy** [comment]
image

But why?

https://core.telegram.org/bots/api#createnewstickerset

**Comment by Badiboy** [comment]
image

Same here:

https://core.telegram.org/bots/api#addstickertoset

**Comment by Badiboy** [comment]
image

image

The existing library style is to have methods name and signature equal to TG signature. I do not think we are ready to change the long-term agreeement. If TG method have "png_sticker" and "tgs_sticker" and do not have "animated" - we should keep them.

**Comment by SwissCorePy** [comment]
> image
> 
> But why?
> 
> https://core.telegram.org/bots/api#createnewstickerset

Because `png_sticker` is now optional and the new `tgs_sticke` too, but `emojis` is not. And in the current `create_new_stickerset` functon, the sticker parameters are in the arguments order before `emojis`. I didnt wanna mess up the arguments order, so i created a extra functon for the animated stickers

**Comment by Badiboy** [comment]
> > image
> > But why?
> > https://core.telegram.org/bots/api#createnewstickerset
> 
> Because `png_sticker` is now optional and the new `tgs_sticke` too, but `emojis` is not. And in the current `create_new_stickerset` functon, the sticker parameters are in the arguments order before `emojis`. I didnt wanna mess up the arguments order, so i created a extra functon for the animated stickers

I found the answer, removed this post and wrote another one ^)

**Comment by SwissCorePy** [comment]
> > > image
> > > But why?
> > > https://core.telegram.org/bots/api#createnewstickerset
> > 
> > Because `png_sticker` is now optional and the new `tgs_sticke` too, but `emojis` is not. And in the current `create_new_stickerset` functon, the sticker parameters are in the arguments order before `emojis`. I didnt wanna mess up the arguments order, so i created a extra functon for the animated stickers
> 
> I found the answer, removed this post and wrote another one :)

Oh sorry i dint see that. Ok i understand what you mean. I will change that :)

**Comment by Badiboy** [comment]
> Oh sorry i dint see that. Ok i understand what you mean. I will change that :)

In this PR, or merge and start new?

**Comment by SwissCorePy** [comment]
In this :)

**Comment by Badiboy** [comment]
Thanks. 

Now I propose to stop with updates (except bugs/mistakes found). I need some time to test it locally, then on production, then we will be able to make a public release. Then we again wait some time for users' feedback (I hope we will not get it :) ) and then we can open the new iteration, if it is neede.

**Pull request merged**
