### PR TITLE
Create method get_media_file_id() in util.py

### PR DESCRIPTION
**Pull request by Cub11k**
## Description
This method is used to get file id of different types of media

## Describe your tests
How did you test your change?

Python version:

OS:

## Checklist:
- [ ] I added/edited example on new feature/change (if exists)
- [ ] My changes won't break backward compatibility
- [ ] I made changes both for sync and async

### CODE REVIEW

**Comment by coder2020official** [comment]
image

I think it would be better to make a list with all content types supported; then use getattr() directly. this would reduce this mess...

**Comment by coder2020official** [comment]
@Badiboy next time please don't hurry with merging

**Comment by Badiboy** [comment]
@coder2020official OK. 

It's functional. If anyone want to optimize it - it will not affect the result. So it can be merged. But OK: I got you.

**Comment by coder2020official** [comment]
@Cub11k will you re-create PR or should I do it myself?

**Comment by Cub11k** [comment]
@coder2020official Sure thing, you can re-create PR

**Comment by coder2020official** [comment]
@Badiboy ?

**Comment by Badiboy** [comment]
I already said my thoughts.

> It's functional. If anyone want to optimize it - it will not affect the result. So it can be merged.

I also think that there is too much attention to trivial update. If you want to optimize it - just do it.

**Comment by coder2020official** [comment]
Read my previous comment. i don't think it should be in the lib.

**Comment by Badiboy** [comment]
I see no problem of being nearly ANY function in the lib. If someone think it is useful (I also think it may be) - why not.

**Comment by coder2020official** [comment]
BRUH
Then why don't we add any other simple functions, such as a function to do if-else?
This function is useless, since the thing can be quickly done through getattr and for loop.
Your thoughts have changed A LOT since my first talk to you - you asked for reason each time i was adding smth new that time. Then why don't u ask for a reason before merging this PR? Why don't u at least wait for my thought?

**Comment by Badiboy** [comment]
Looks like you have a lot of free time to discuss this update...

> you asked for reason each time i was adding smth new that time.

You tried to do it in the MAIN ENGINE. In the main engine useless or very rarely used things affects the performance of all millions of systems build on this library. Functions in util do not affect anything until you call them.

More then a year had passed. You still do not understand the difference between main engine and utils. That's sad.

**Comment by coder2020official** [comment]
Let me remind you: my functions were not mostly based on MAIN ENGINE, as you said. They were mostly functions in main class. So, technically they are the same as functions in util - they don't mess up until you call them.
And you asked for a reason each time. Even when i was adding features like custom filters / states. That seemed to be ridiculous, however, now you need to do that before merging.

The sad thing is that you no more ask for reasons and don't wait for my opinion. Don't make your resentment or personal opinion ruin the project.

**Comment by coder2020official** [comment]
So, I'd better ask to remove this function since it is useless. Your opinion?

Note that i never merge PRs unless it is docs-related or some minor improvement is made. I've always asked for your opinion and I 'd ask you to do the same.

**Comment by Badiboy** [comment]
I can not waste any more time to repeat the same thing I said already 2 times. Just read above.

**Comment by coder2020official** [comment]
Ok then I'll make PR with deletion of this func

**Comment by Badiboy** [comment]
No, not OK. Read again.

**Pull request merged**
