### PR TITLE
Added poll_example.py in the examples

### PR DESCRIPTION
**Pull request by Muhammad-Aadil**
## Description
An example file on how to create polls and handle poll answers

Python version:  3.9.7

OS: Ubuntu 20.04.1

### CODE REVIEW

**Comment by coder2020official** [comment]
I'd recommend making quiz type poll instead

**Comment by Muhammad-Aadil** [comment]
You mean something like this:
`    poll = bot.send_poll(
        chat_id=message.chat.id,
        question="We are going to '' park.",
        options=answer_options,
        **type='quiz',
        correct_option_id=2,**
        is_anonymous=False,
    )`

**Comment by coder2020official** [comment]
Yes. I think this would be better, no?

**Comment by Muhammad-Aadil** [comment]
Yes, it is better, How about we add both?

**Comment by coder2020official** [comment]
I don't think both will look good, since for quizes quiz mode should be used.

**Comment by Muhammad-Aadil** [comment]
Hi! Yes, you are absolutely right.

**Review by coder2020official — APPROVED** [review]
Looks fine, any ideas or review @Badiboy ?

**Comment by coder2020official** [comment]
@badiboy can u merge this and look at my bot api pr? since u have unsubscribed from notifications i was unsure whether u were getting an email about me tagging u there.

**Pull request merged**
