### PR TITLE
Changes in deprecated parameters for async

### PR DESCRIPTION
**Pull request by coder2020official**
Separated allow_sending_without_reply and reply_to_message_id into 2 different if-elses for each methods;
Planning to add hcite and mcite

### CODE REVIEW

**Comment by coder2020official** [comment]
Btw, Badiboy, I noticed one thing: the order of parameters in a function is changed for deprecation-related methods. I think it will cause some issues after release. So for example, here is send_document:
image
I know passing arguments by their position is never recommended, however, don't you think this will cause issues after the release?

**Comment by Badiboy** [comment]
> I know passing arguments by their position is never recommended

As for me, I don't think we should care about ones, who passes named parameters by position...

For this case it was not necessary: I changed the place of parameters because it helped me to update lot of functions. If you hardly care about all species - we may rollback that. We mostly means "you", because have neither time nor willing...

**Comment by coder2020official** [comment]
I will find time to do that then. Don't wanna see reports regarding crashes after release

**Comment by coder2020official** [comment]
I think it is time to check the PR

**Comment by coder2020official** [comment]
@Badiboy you are here and aware that I am done with PR right? Just asking

**Comment by Badiboy** [comment]
@coder2020official Sorry, I missed your request. Checking.

**Review by Badiboy — APPROVED** [review]

**Comment by coder2020official** [comment]
I will go through one last time and notify you when everything is ready for release - is that fine?

**Comment by Badiboy** [comment]
yep

**Pull request merged**
