### PR TITLE
Some Updates

### PR DESCRIPTION
**Pull request by SwissCorePy**
* Added lot of type hints to types.py
* Added some new fields from TelegramBotAPI to pyTelegramBotAPI
* Fixed `circular import error` in util.py
* Added functions `log_out` and `close` to __init__.py and apihelper.py
* And some more small changes

### CODE REVIEW

**Comment by Badiboy** [comment]
1. Your previous commit broke the library. I asked you to fix it ASAP, because project building fails. You ignored it and post new update (may be with fix) 10 days later. It's unacceptable.
2. Your new update fails with the same errors. It means that you even not tested updates before commit them. This is also not acceptable approach. 

If you will continue this way I will be forced to decline your updates.

**Comment by SwissCorePy** [comment]
>     1. Your previous commit broke the library. I asked you to fix it ASAP, because project building fails. You ignored it and post new update (may be with fix) 15 days later. It's unacceptable.

> 
>     2. Your new update fails with the same errors. It means that you even not tested updates before commit them. This is also not acceptable approach.
> 
> 
> If you will continue this way I will be forced to decline your updates.

1. Oh I'm sorry. I did not know that my previous update broke the library where did you ask me to fix it? I got no Email.
2. I testet with python 3.9. Can you tell me a easy way to test it with multiple python versions? I worked 5 hours on that code yesterday to help improve the library. Its definitely not my goal to break it.

**Comment by Badiboy** [comment]
1. https://github.com/eternnoir/pyTelegramBotAPI/pull/1176#issuecomment-854178961
2. Python 3.9 also fails. See Build report below.

**Comment by Badiboy** [comment]
image

**Comment by SwissCorePy** [comment]
I'm going throgh the logs now and try to fix everything.
Sorry for the inconvenience.

**Pull request closed without merging**
