### PR TITLE
new: add register_next_step_handler for asyncbot

### PR DESCRIPTION
**Pull request by hiddify-com**
## Description
create missing 
register_next_step_handler  in asyncbot using auto state

## Describe your tests
run step_example.py in async_telebot

Python version:

OS:

## Checklist:
- [*] I added/edited example on new feature/change (if exists)
- [*] My changes won't break backward compatibility
- [*] I made changes both for sync and async

### CODE REVIEW

**Comment by coder2020official** [comment]
No

**Comment by hiddify-com** [comment]
why?

**Comment by coder2020official** [comment]
1. Bad implementation 
2. No steps in async please

**Comment by hiddify-com** [comment]
It is based on your recommendation that suggest to use state

It is really useful to have steps in async

The step in sync is buggy also. It does not process middlewares.

**Comment by coder2020official** [comment]
Steps are an old, somewhat "deprecated"(though not yet and won't probably), so there's no point of improving them when there's a solution(states) which I am currently working on to even further improve

**Comment by hiddify-com** [comment]
the problem of state is that we can not have more complex workflow
for example when we want to get 10 elements from user it is so hard to be implemented by state

**Comment by coder2020official** [comment]
What do you even mean by "10 elements"?
10 inputs?
I am working on an easier solution, some class that will take care of this

**Comment by hiddify-com** [comment]
yes 10 inputs from the user

great thanks

**Comment by hiddify-com** [comment]
@coder2020official Thanks for your great job. It would be great if we can have a timeline about your solution

**Comment by coder2020official** [comment]
Hi, my solution never came to existence, and I haven't had enough time recently either. I wouldn't mind re opening this.

I'm open to proposals, or I'll look at this issue again in December and see if there's any way I can simplify states logic.

Also, I have re implemented states to make them easier to use :)

**Comment by coder2020official** [comment]
I'll open an issue

**Comment by hiddify-com** [comment]
Thanks

**Pull request closed without merging**
