### PR TITLE
Add type hints to SimpleCustomFilter

### PR DESCRIPTION
**Pull request by vehlwn**
## Description
Resolves https://github.com/eternnoir/pyTelegramBotAPI/issues/2250

## Describe your tests
How did you test your change?

Python version: 3.12.3

OS: Arch Linux

## Checklist:
- [ ] I added/edited example on new feature/change (if exists)
- [x] My changes won't break backward compatibility
- [ ] I made changes both for sync and async

### CODE REVIEW

**Comment by coder2020official** [comment]
Filters are not always types.Message

**Comment by coder2020official** [comment]
This is wrong

**Comment by Badiboy** [comment]
Mmmm... Thus not so good naming. What can be passed as message except Message?

**Comment by coder2020official** [comment]
Callback data, for example. Or any other update type

**Comment by Badiboy** [comment]
Rename parameter do "data" and set hint to "Any"?

**Comment by coder2020official** [comment]
Don't worry about any typehints for now. I will try to work on them when I'm free

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2252

**Pull request merged**
