### PR TITLE
there is no redis.asyncio.__version__

### LINKED ISSUE #2010: AttributeError: module 'redis.asyncio' has no attribute '__version__'
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.12.0

3. What OS are you using? linux

4. What version of python are you using? 3.10

when using async StateRedisStorage, redis.asyncio do not have __version__ attr so this code raises error

[asyncio](https://github.com/eternnoir/pyTelegramBotAPI/blob/3960115ec7cd9612e7985840c7e6dd40a48c1ffb/telebot/asyncio_storage/redis_storage.py#L5C1-L30)

### PR DESCRIPTION
**Pull request by engAmirEng**
-fixes #2010

## Checklist:
- [x] My changes won't break backward compatibility

### CODE REVIEW

**Comment by Badiboy** [comment]
It's a bit useless to check redis version: it is 3+ loooong ago. I propose to check only aioredis version.

image

And do not check in redis branch.

**Comment by engAmirEng** [comment]
> It's a bit useless to check redis version: it is 3+ loooong ago. I propose to check only aioredis version.
> 
> image
> 
> And do not check in redis branch.

We should find the redis version in which aioredis version 2 is contained and check against that version

**Comment by Badiboy** [comment]
I propose to check only aioredis version.
And do not check version in redis branch, because it's useless.

**Comment by Badiboy** [comment]
You bring the problem back.

```
if is_actual_aioredis:
    aioredis_version = tuple(map(int, aioredis.__version__.split(".")[0]))
    if aioredis_version < (2,):
        raise ImportError('Invalid aioredis version. Aioredis version should be >= 2.0.0')
```

**Comment by engAmirEng** [comment]
@Badiboy I don't think so, problem was in redis not aioredis itself

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2015

**Pull request closed without merging**
