### PR TITLE
Fix list objects in methods

### PR DESCRIPTION
**Pull request by coder2020official**

### CODE REVIEW

**Comment by coder2020official** [comment]
@badiboy you think this doesn't require an extra release?

**Comment by Badiboy** [comment]
I started testing the release and also found this bug. ) And other more sensitive. 

Yes, it will require a bugfix release.

**Comment by coder2020official** [comment]
Could you carry out more tests and release a new version then?

**Comment by Badiboy** [comment]
Yep, I will.

**Pull request merged**
