### PR TITLE
Added my bot made using pyTelegramBotAPI

### PR DESCRIPTION
**Pull request by tusharhero**
## Description
source code available here 
https://github.com/tusharhero/bincode-telegram-bot

## Describe your tests
How did you test your change?

Python version:

OS:

## Checklist:
- [x] I added/edited example on new feature/change (if exists)
- [x] My changes won't break backward compatibility
- [x] I made changes both for sync and async

### CODE REVIEW

**Comment by Badiboy** [comment]
Why you decided to add your bot to the front of the list?

**Comment by tusharhero** [comment]
> Why you decided to add your bot to the **front** of the list?

Where are we supposed to add it?

**Comment by Badiboy** [comment]
To the end, after the last record...

**Comment by tusharhero** [comment]
> To the end, after the last record...

ok done

**Comment by Badiboy** [comment]
👍

**Pull request merged**
